### ISSUE TITLE
Create Q1 branding plan for Webmaker, Teach, Learning, and Hives / "Mozilla Learning"

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#152]
## Problem
We need clarity around next steps for wider branding issues. I've created a plan to reach that clarity by dividing the work into Congruency, Research, Design & Implementation phases. Altogether should take 10 weeks to complete, the length of which is because of the level of detail and cross-team effort involved + scope of work to implement the changes.

### Audience
everyone!

### Success
Webmaker properties will have updated branding that is consistent and cohesive with wider Mozilla branding. Our branding (and accompanying documentation) is up-to-date, reflects an intuitive relationship amongst Mozilla initiatives, and is aesthetically and structurally forward-thinking.

## Phase 1: Congruency

Meet with MaryEllen / Sean Martell / Geoffrey to discuss how Webmaker fits in with wider Mozilla branding plans (happening the week of Dec 16)
Identify team and stakeholders
Clearly scope to individual brands, if possible
* Is this exercise necessary for Learning and/or Webmaker
* Does 'Learning' branding fall under our domain (or MoCo's)
* Do Hive and teach.webmaker.org need additional, parallel branding work

**Deliverables:**
* Revised scope document (this bug): answer Q re scope of work: Webmaker / Mozilla Learning / Teach.webmaker / Hives ?
* RACI for phases 2 & 3

-----------------------------

## Phase 2: Research

**Week 1: Information gathering**
Draft up a brand survey for identified stakeholders. 
* What are users' and partners' expectations of the Webmaker brand
* What are the existing brand qualities that we can build on
* Audit existing strengths and weaknesses
* What other factors will influence branding success (geographies, plans, etc)
* Do we want to use Mozilla or Firefox brands?
* Do people understand the relationship/s between Mozilla / FF / Webmaker / Hives?
Build the brand survey out and prep for launch. Identify who to send it to.
Work with product to begin a competitor brand analysis

**Week 2: Brand landscape**
Launch the brand survey early in the week
Finish off the competitor brand analysis w/ identified stakeholders

**Deliverables:**
* launched brand survey; some feedback coming in.
* competitor brand analysis document

-----------------------------

## Phase 3: Brand analysis and exploration 

**Week 1: Analysis**
Close the branding survey & begin analysis
Identify opportunities to evolve Webmaker's brand
Identify how we can differentiate Webmaker's brand from competitors
Begin brainstorming when ready (not necessary to wait for week 2)

**Week 2: Brainstorming**
Inspire next steps w/ visual brainstorming
Set metrics we can use to measure branding exercise success
Revise scope for next phase (what will it take to implement)

**Deliverables:**
Completed Brand Survey analysis doc
Visual brainstorming doc
Success metrics identified and in place

-----------------------------

## Phase 4: Brand evolution & documentation

**Week 1: Refine the relevant brand/s**
User test visual brainstorming doc
* Can Laura help us with this in the field?
Brand revisions: update the style guide
* Logo/s (webmaker + tools)
* Colour & typography palettes
* Imagery (photography & illustration)
* UI & interactions
* Animation
Send for approval from all necessary stakeholders

**Week 2: Revise
First blast of revisions (subject to feedback and user test results)**
Begin implementing major changes
* nav bar
* ... TBD
Check in on success metrics

**Deliverables:**
Results from a user test
Updated & approved style guide (published online) & documentation in the Design Handbook
Bugs filed for implementing the changes

-----------------------------

## Phase 5: Brand consistency

Brand update (& de-branding?)
* Webmaker desktop (incl. tools)
* Webmaker app
* teach.webmaker.org
Revise scope for next phase
Final finesse; followup bugs
Check in on success metrics

-----------------------------

#### MVP
Brand survey + updated style guide + implemented changes across properties

### Risks
This initiative requires wide cross-team collaboration between Mofo & Moco. We should test implementations to ensure cultural relevancy. Difficult to define branding success metrics. Implementing changes may require significant followup effort.

## Preparation Checklist

 - [ ] Kickoff meeting scheduled.
 - [ ] Deadline and flexibility established.
 - [ ] Localization plan created.
 - [ ] Milestones created.
 - [ ] Maintenance plan created.
 - [ ] Analytices plan created.
 - [x] Scope creep avoided.

## RACI

(for Phase 1: Congruency)
* Phase: Research
* Owner: @mw or @secretrobotron
* Consulted: maryellen, @mart3ll, geoffrey, @HPaulJohnson, claw, michelle
* Decision Maker: @cassiemc
* Design Lead: TBD (branding)
* Development Lead: TBD (frontend)
* Quality Verifier: @thisandagain

**Comment by OpenMatt** [comment]
Revised title of this ticket to more clearly focus the goal.

Next step: Jan 6 project kick-off meeting will document roles and next steps. 
a) clearly identify roles & owner. (for the next heartbeat or two -- owners and roles will change as we go) 
b) agree on what's time-sensitive / urgent here. what *specifically* do we need to achieve on this file in Q1?
c) untangle threads. there's lots of different strands of work here -- let's make sure we untangle them. 
d) ensure good co-ordination w. ops.

**Comment by cassiemc** [comment]
@OpenMatt I filed #179 as a smaller scope for this heartbeat. I'd like to keep this meta ticket open though to see the whole exercise in one place. I'll remove the jan16 & p1 labels from this issue. Can you add your thoughts to #179, if still relevant?

**Comment by cassiemc** [comment]
A lot has changed here, so I'm going to close this. But we can keep it for a reference for #644 and maybe #209 (closed)
