### ISSUE TITLE
Design teach.wm.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#285]
This is a parent ticket for all of the design work for the teach site. Child tickets are located in the Mozilla-Learning repo.

### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* UI Design: @vazquez
* UX Design: @iamjessklein 
* Dev Lead: NA. See related dev ticket.
* Quality: @davidascher 
* Metrics: NA. See related dev ticket.

### Deliverables

February 13 heartbeat
 - [x] Design homepage (https://github.com/MozillaFoundation/Mozilla-Learning/issues/5)

February 27 heartbeat
 - [x] Design Clubs Curriculum page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/36)
 - [x] Design Clubs page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/6)
 - [x] Design "Add Your Club" workflow (https://github.com/MozillaFoundation/Mozilla-Learning/issues/70)

March 13 heartbeat:
 - [x] Polishing of Clubs Curriculum page (i.e. incorporate last bit of redpen feedback, give assets to engineers)
 - [x] Polishing of "Add Your Club" workflow (i.e. incorporate last bit of redpen feedback, give assets to engineers)
 - [x] Design "Indicate your interest" workflow (https://github.com/MozillaFoundation/Mozilla-Learning/issues/97)
 - [x] Design "Teach Like Mozilla" page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/37)
 - [x] Design Web Literacy page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/52)
 - [x] Design About page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/99)

March 27 heartbeat:
 - [x] Design Events page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/35)
 - [x] Design Teaching Activities page

Kickoff notes here: https://etherpad.mozilla.org/teach285
User testing results from early wireframes: http://mzl.la/1zhj6UQ

**Comment by OpenMatt** [comment]
@hannahkane all "Plan" tickets need a RACI. Please fill in what you can above. Will work to finalize the rest in Heartbeat planning meeting etc.

**Comment by cassiemc** [comment]
This sounds a little broad, @hannahkane can you help clarify what is being designed here? Do you mean just the homepage?

**Comment by hannahkane** [comment]
I meant the full v1 of the site. Will need help right-sizing for a single heartbeat.

**Comment by cassiemc** [comment]
@hannahkane Are there finalized wireframes?

**Comment by hannahkane** [comment]
No, we're testing wireframes this week.

**Comment by OpenMatt** [comment]
@cassiemc could use an estimate from you on amount of effort required here.

**Comment by cassiemc** [comment]
Assigning myself to design here. The timing works out as I should be finished with Call Congress by the time this kicks off.

**Comment by OpenMatt** [comment]
Assigning @hannahkane as decision-maker here.

**Comment by hannahkane** [comment]
@cassiemc and I have a kick-off meeting scheduled for Wednesday (tomorrow). Will have some initial user testing results to share at that point.

**Comment by cassiemc** [comment]
Pumped :)

**Comment by OpenMatt** [comment]
@hannahkane are there links to wireframes we can look at? can you add them here?

**Comment by OpenMatt** [comment]
Wireframes being tested:
http://marvl.in/b0ah39
http://marvl.in/11ji896

**Comment by hannahkane** [comment]
Moved kick-off meeting to Friday so @davidascher can attend.

User testing results started here, though there's one other to add so far: http://mzl.la/1zhj6UQ

**Comment by cassiemc** [comment]
@hannahkane Is there a new information architecture I can see somewhere? Should we be filing individual tickets for this meta bug somewhere else?

**Comment by cassiemc** [comment]
I filed a bunch of new issues here – https://github.com/MozillaFoundation/hannah-barbera/issues
Maybe we can clarify the scope of this ticket on monday? In the meantime, plenty for me to move on!

**Comment by OpenMatt** [comment]
* Outstanding work on this ticket @hannahkane. Plus lots of great design progress already from @cassiemc 
* **Key questions for kick-off meeting:**
1) What's the right amount of design work to bite off this Heartbeat?
2) How do we phase with dev? So that we can optimize the hand-off between design and build? 
3) What's our strategy for avoiding waterfall-ish-ness on this project in general, and pushing for more agility?

**Comment by OpenMatt** [comment]
+ @adamlofting to help ensure we're tracking the metrics we need. Would be good if Adam was in the kick-off meeting for this.
* once we launch the initial pages, what experiments are we going to run?

**Comment by adamlofting** [comment]
Thanks @OpenMatt - I'm going to move the metrics requirement for this piece across the to corresponding `build` ticket, and ask my questions there. 
@hannahkane I'm happy to attend the kick-off, but if scheduling proves hard due to me, we can check-in separately.

**Comment by hannahkane** [comment]
kick-off meeting scheduled for 9:30am PT on Wednesday

**Comment by hannahkane** [comment]
Updated description to reflect the pieces we committed to for this heartbeat.

**Comment by hannahkane** [comment]
Daily progress check: Progress was made on both of this heartbeat's tickets today. See MozillaFoundation/Mozilla-Learning#36 and MozillaFoundation/Mozilla-Learning#6 for more.

**Comment by hannahkane** [comment]
Much progress today, both on the Teaching Materials and Clubs pages, and in terms of crystallizing some outstanding questions: https://etherpad.mozilla.org/teachsitequestions (to be discussed with @thornet and others early next week)

**Comment by hannahkane** [comment]
A bit on hold, given design work week.

**Comment by chrislarry33** [comment]
understandable

**Comment by cassiemc** [comment]
Just confirming @vazquez and I are doing UI design for this heartbeat. Also adding @iamjessklein to help support with UX & design reviews.

**Comment by hannahkane** [comment]
Awesome. Sent an invite for a kick-off meeting tomorrow at 1pm ET.

**Comment by iamjessklein** [comment]
:+1: kickoff! :soccer:

**Comment by hannahkane** [comment]
Mic check update: had a kick-off meeting yesterday. Designers have flagged lack of final content as a blocker. Taking steps to resolve including establishing deadlines for final content (but, alas, they are mid-heartbeat).

**Comment by hannahkane** [comment]
Moving this ongoing work to March 27th heartbeat.

**Comment by cassiemc** [comment]
Have assigned @vazquez and @iamjessklein to carry on the work from before. Please feel free to use me as a resource for design review.

**Comment by hannahkane** [comment]
Update for those who are interested:
During today's stand-up, Jess and Ricardo assigned themselves to the last few full page designs that need to happen. woot!

**Comment by hannahkane** [comment]
Update: There are currently 5 remaining tickets in the Design queue.

https://github.com/mozilla/teach.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3Adesign+milestone%3A%22March+27%2C+2015%22+label%3Aplatform

Based on today's stand-up, they are all likely to finish by the end of the heartbeat, with the exception of the "CSS fixes" ticket which will likely take another day.

**Comment by hannahkane** [comment]
All of the substantive design work for v1 is complete. The only remaining tickets are for CSS tickets and QA work, which will be covered by another /plan ticket in the next heartbeat.

Woohoo! Nice job, @vazquez, @iamjessklein, and @cassiemc!!!

**Comment by iamjessklein** [comment]
:shipit: yay! :dancers:
