### ISSUE TITLE
Soft-launch teach.webmaker.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#338]
This is a parent ticket for all of the engineering work for the teach site. Child tickets are located in the Mozilla-Learning repo.

### RACI
* Phase: Build
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: NA (see design ticket #285 )
* Dev Lead: @toolness 
* Dev: @alicoding 
* Quality: @davidascher 
* Metrics: @adamlofting

### Deliverables

February 27 heartbeat: 
 - [x] Clone mofo-example app and push to https://teach.mofostaging.net/ (https://github.com/MozillaFoundation/Mozilla-Learning/issues/69)

March 13 heartbeat:
 - [x] Build homepage (https://github.com/MozillaFoundation/Mozilla-Learning/issues/40)
 - [x] Build Clubs page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/44)

March 27 heartbeat:

 - [x] Build Events page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/41)
 - [x] Build "Teach Like Mozilla" page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/43)
 - [x] Build Web Literacy page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/51)
 - [ ] Remove redundant content from Webmaker.org (https://github.com/MozillaFoundation/Mozilla-Learning/issues/55)
 - [x]  Setup Analytics / Metrics for teach.webmaker.org (https://github.com/MozillaFoundation/Mozilla-Learning/issues/57)
 - [x] Build "Add Your Club" workflow (https://github.com/MozillaFoundation/Mozilla-Learning/issues/71)
 - [ ] Build sign-up flow (https://github.com/MozillaFoundation/Mozilla-Learning/issues/46)
 - [x] Build Clubs Curriculum page (https://github.com/MozillaFoundation/Mozilla-Learning/issues/42)

**Comment by OpenMatt** [comment]
@hannahkane can you be more specific about which of those "build" tasks are going to be ready to start building this Heartbeat, and when? e.g., which will have completed design ready to hand off, and roughly when that's expected to happen.
* A good kick-off meeting on this ticket should help design and dev focus on hand-off and phasing together

**Comment by OpenMatt** [comment]
* I'm also going to suggest we break this into "Phases", a practice we've used in past for multi-heartbeat tickets like this one.

**Comment by hannahkane** [comment]
I don't know which will be ready to go, as I haven't had a conversation with @cassiemc about estimating the design work timeline. I was planning to discuss this during the kick-off meeting.

**Comment by hannahkane** [comment]
kick-off meeting scheduled for Wednesday at 9:30am PT

**Comment by hannahkane** [comment]
Updated description to reflect outcome of kick-off meeting which is that the "build" part of this heartbeat will focus on prototyping the technical solutions for allowing staff to maintain the site. @simonwex and @jbuck to add more specific tickets to capture that work.

**Comment by hannahkane** [comment]
These are the heartbeat deliverables, as per today's stand-up:
 - [ ] Create home page based on Cassie's designs
 - [ ] Implement at least two proposals as prototypes for content-editing the home page by members of the Mentor Networks team
 - [ ] Evaluate ease of use for prototypes with Hannah, Michelle, Lainie

**Comment by hannahkane** [comment]
Commenting to demonstrate life. Stuff is happening. See https://github.com/MozillaFoundation/Mozilla-Learning/issues/75

**Comment by hannahkane** [comment]
@simonwex - do you know who will be assigned to this? Wondering who I should invite to the kick-off!

**Comment by simonwex** [comment]
@hannahkane all the devs are listed in the RACI above.

**Comment by hannahkane** [comment]
Ah, sorry, missed that. Thanks!

**Comment by hannahkane** [comment]
Mic check update: had a kick-off yesterday with lots o' people. @simonwex created a new repo (/mozilla/teach.webmaker.org) and many tickets have been added and worked on.

**Comment by hannahkane** [comment]
Moving this ongoing work to March 27th heartbeat.

**Comment by hannahkane** [comment]
@simonwex - are @toolness, @alicoding, @mmmavis (until Tuesday), and @gesa still assigned to this ticket?

**Comment by ScottDowne** [comment]
This just caught my attention and I see my name listed as a dev. I have no context for this yet but is there something I should be looking into now or is this work still being... scoped?

**Comment by hannahkane** [comment]
Hey @ScottDowne - looks like you've been assigned to this project. Yay! The project is scoped. I'll send you and @toolness a calendar invite to help get you up to speed.

**Comment by hannahkane** [comment]
Update for interested people: 

We invited the team working on new login to join our stand-up today, but it was a little premature since we haven't had the login kick-off yet. Regardless, was good to have everyone on the call. 

Assigned several tickets to begin work today - building the static pages that aren't blocked on design, and wiring up all of the modal stuff.

**Comment by hannahkane** [comment]
An important update for anyone interested in the Teach v1 release schedule!

/cc @chrislarry33 @ldecoursy @thornet @amirad @davidascher @OpenMatt @simonwex @cassiemc @toolness @ScottDowne @iamjessklein @vazquez @gesa @alicoding @jbuck @jdotpz @HPaulJohnson @KevZawacki 

**Bottom line:** Though it's possible we could be ready to release on Monday, I think it would be wiser to plan to delay for at least two days. I don't personally feel the Webmaker login experience should be a blocker to release, but will defer to @chrislarry33 on that point. (When I say "release," I'm referring to the technical task of moving it to the production server. We could choose to not tell anyone about it. :))

**More detail:**
There are currently 24 open tickets in the engineering queue:

https://github.com/mozilla/teach.webmaker.org/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aengineering+milestone%3A%22March+27%2C+2015%22+label%3Aplatform+
 [[unflagged]](http://plzkthx.herokuapp.com)

 * Six of them are building out pages of the site. One of those is currently blocked on design, and another is likely to be a bit of a doozy since it involves some on-page interactions (eg. hover states, tabs that reveal content when clicked). The others are in progress.
 * Two are workflows (edit your club, delete your club) that are nearly finished, I believe.
 * Three of them are map-specific bugs—solutions are in progress for all of those.
 * Eight of them are minor copy changes, bugs, or enhancements.
 * Four are technical issues. I'll get clarity at tomorrow's stand-up about the priority of these.
 * The last is not technically a requirement for launch (removing redundant content on Webmaker.org)

**Additional potential blockers:**
 * Importantly, we may decide that the site launch is dependent upon completing the login work that's happening in the id.webmaker.org project. We do not expect that project to be complete and incorporated by the end of this heartbeat (though much good progress is being made!)
 * As far as I know, we don't yet have the domain and SSL cert yet. As I understand it, those are blocked on Moco.

**Likelihood of releasing at the end of this heartbeat:**
 * Design work will likely be complete, though I expect we'll want an extra day or two for design review and CSS fixes
 * I expect most of the pages, the map fixes, and the minor changes will be complete at the end of the heartbeat. I expect two pages will *not* be complete—the Events Resources page, which requires extra front-end interaction work, and the Toolkit page, which will likely be blocked on design until Thursday.
 * We can be doing QA in the meantime, but we'll want to have extra time for QA after all of the above is complete.
 * If we want the Webmaker login experience to be a part of the release, we will have to wait until that project is complete. Note: this is *not* technically a blocker since we do have a fallback experience implemented already (Persona).

**Comment by chrislarry33** [comment]
Thanks @hannahkane these recommendations make sense to me and I say lets move forward as you suggest

**Comment by iamjessklein** [comment]
:+1:

**Comment by hannahkane** [comment]
Moving this ticket to the next heartbeat. It's *very* close, but there are still several tickets in the queue, plus QA work that will happen at the beginning of the next heartbeat.

**Comment by hannahkane** [comment]
Moving this to the next heartbeat again. Pending:
 - [ ] new login to be polished by id team
 - [ ] outstanding small tasks to be completed by teach team
 - [ ] @simonwex to make sure all boxes are checked on https://github.com/mozilla/teach.webmaker.org/issues/152

**Comment by iamjessklein** [comment]
we can get there! :horse_racing:

**Comment by OpenMatt** [comment]
@hannahkane will file a security review ticket for wex.

**Comment by hannahkane** [comment]
Security review for @simonwex : https://github.com/mozilla/teach.webmaker.org/issues/680

**Comment by hannahkane** [comment]
EOD update: 
outstanding tickets that are blockers are here: https://github.com/mozilla/teach.webmaker.org/issues?q=is%3Aopen+milestone%3A%22Inspector+Gadget%22+label%3Av1

Launch will likely happen tomorrow.

**Comment by hannahkane** [comment]
Waiting one more day. There's one outstanding id.webmaker issue.

**Comment by hannahkane** [comment]
DOOOOOOONE!!!!

**Comment by jgmac1106** [comment]
Just went to teach.mozilla.org on the phone. Congrats to all! Been quite
the pleasure to watch you work.

**Comment by amirad** [comment]
:boom: 

:clap::clap::clap::clap:

**Comment by cassiemc** [comment]
Amazing! Nice work everyone! :+1:

**Comment by toolness** [comment]
Hooray!!!!

Just so everyone knows, there are still a few [minor things to work out](https://github.com/mozilla/teach.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3Av1) but they should be resolved by the end of the day.

**Comment by xmatthewx** [comment]
Congrats everyone!!

**Comment by jgmac1106** [comment]
I was able to log in immediately and brought me right to the register your
club page. Amazed you got log in ready for the hardening but still soft
launch.
