### ISSUE TITLE
Develop Content Strategy for Webmaker launch

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#428]
**Goal**: Develop a content strategy for the launch of Webmaker. Should include audiences, scheduling, logistics and feedback mechanisms.

**Doc**: (WIP)
* ~~https://docs.google.com/a/mozillafoundation.org/document/d/14K93EYq1ayzkhvrXoXZPNTdulEfVhtIxBQgrHxIpBsQ/edit~~
* https://docs.google.com/document/d/125EsGZkf_bRKsZQT5L3VDFYs0NMXpV9J_ce8t1S-4fo/edit

**Bugs**:
* Webmaker App: https://github.com/mozilla/webmaker-app/labels/Content

**ToDo**
- [x] Talk to Paul to develop ideas
- [x] Talk to George about MoCo plans
- [x] Refine document
- [x] Regular check-ins w/ Paul
- [ ] Draft design for Maker Party activity w/ teach team
- [ ] Gather lots of contacts to ask about helping with content
- [ ] Track regions and content coverage

### RACI
Phase: Design
Driver: @secretrobotron
Decision: @HPaulJohnson 
Quality: @thisandagain, @adamlofting

**Comment by cassiemc** [comment]
I can help here too, if you need me.

**Comment by LauraReynal** [comment]
I have lots of feedback and ideas from the testing here in Chicago about what would attrack users and their reactions towards our existing ideas.

**Comment by OpenMatt** [comment]
@secretrobotron status update?

**Comment by secretrobotron** [comment]
Some work done, but need to  continue to refine. Moving to next milestone.

**Comment by thisandagain** [comment]
Tracking plan here: https://docs.google.com/document/d/125EsGZkf_bRKsZQT5L3VDFYs0NMXpV9J_ce8t1S-4fo/edit

**Comment by secretrobotron** [comment]
Thanks @thisandagain . Very much a WIP. Will break up into more readable pieces.

**Comment by OpenMatt** [comment]
@secretrobotron status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by secretrobotron** [comment]
Lots of good work last heartbeat with @HPaulJohnson. Will be part of larger Webmaker launch plan. Continuing work in #460.
