### ISSUE TITLE
Create interstitial experience for Surveillance snippet campaign

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#435]
The Surveillance Campaign (Section 215) is going to get some time on the US-EN snippet. We need to create an intermediate (also known as interstitial) page between the snippet and the petition to ensure only the FF users who are interested are directed to the petition.

#### RACI:
Driver: @edrushka
Design: @cassiemc and @flukeout 
Dev: @ScottDowne 
Metrics: @adamlofting 
Decision Maker: @valianttry (who will also act as liaison for MoCo signoffs)
Informed: @simonwex @DaveSteer @OpenMatt  

#### Milestones:
- [x] Design finalized: Friday April 24
- [ ] Build finalized: Wednesday April 29 EOD
- [ ] QA: Thursday April 30
- [ ] Snippet dates: Friday May 1 to May 15 (to be confirmed, and dependent on conversion rates)

#### Individual tickets:
Design ticket: https://github.com/MozillaFoundation/movement-building/issues/40
Build ticket: https://github.com/MozillaFoundation/movement-building/issues/41
QA ticket: https://github.com/MozillaFoundation/movement-building/issues/42
Metrics ticket: https://github.com/MozillaFoundation/movement-building/issues/43

**Comment by davidascher** [comment]
Not sure where to ask this question, so asking here:
 - What domain hosts the interstitial ticket?
 - make sure to add google analytics to that interstitial. /cc @adamlofting.

**Comment by ScottDowne** [comment]
@davidascher "What domain hosts the interstitial ticket?" A simple page in BSD?

**Comment by davidascher** [comment]
@ScottDowne BSD pages are under 'donate.mozilla.org' or 'sendto.mozilla.org' IIRC.  Is that appropriate?  If the page isn't hosting PII, why would we use BSD?  (Not saying we shouldn't, just want the decision made thoughtfully).

**Comment by ScottDowne** [comment]
@davidascher Yeah, it doesn't need to be on BSD.

 It would be on sendto.

My only logical reason is it keeps all the surveillance pages under one service and I have everything I need to create the page.

**Comment by edrushka** [comment]
FYI: I've booked a daily standup
**1:00pm ET/10:00 am PT**
**Erika's vidyo room**
All are welcome.

**Comment by edrushka** [comment]
Update: 
Luke and Cassie combined forces to create a super design: https://redpen.io/oz58598d25c83f62ca 
MoCo is currently reviewing.
If we're moving ahead with this, Scott will build next week.

**Comment by OpenMatt** [comment]
Nice work guys! so @edrushka : sounds like next steps to close this one are: 
- 1) get design approved by MoCo
- 2) then close this ticket and create a new build ticket this heartbeat (assigned to Scott)

**Comment by cassiemc** [comment]
Here's the feedback from Moco via email. Mostly copy changes:
* Love the education and the conditional “answers” given to users.
* Love the eyeball!
* The site doesn’t explicitly call out that Mozilla is for “stopping mass surveillance.” Maybe this can be woven into the petition CTA.
* Right now the petition CTA is to “help make civil liberties an important part of the conversation,” but the petition itself is more aggressive than this. Want to be super clear to our users. Maybe we say something to the nature: “Mozilla has this stance. If you agree based on what you’ve learned, sign this petition to XXX.”
* There is exact repetitive language ending the response we give to people who click “No” on questions 2 and 3. Potential risk here in that users will have already seen that language and may not read the more important first sentence of Question 3 thinking it is the same thing as they just read. Suggest removing the last sentence of response to Question 3 or rewording it so that it is different than response 2.
* The mock up doesn’t have language for responses to Question 1 “No” or Questions 2 or 3 “Yes” -- could we review?
* There is a disconnect with the headline copy “If I’m not under investigation…” and the subsequent questions. (We see where you are taking this but it’s not intuitive.)
* I don’t think it’s clear enough in the copy that this is the current state of affairs, and I can change anything.
  * “The U.S. government currently monitors…”
  * “As it stands today, the Patriot Act provision…”
  * “Right now, the Patriot Act does allow for…

**Comment by edrushka** [comment]
This is the meta ticket so I'm leaving it open until the project is done. 

Update:
Design is done: MozillaFoundation/movement-building#40
Build starts today: MozillaFoundation/movement-building#41

**Comment by OpenMatt** [comment]
note: MoCo approved the design :)

**Comment by cassiemc** [comment]
Here's the milestone for launching this: https://github.com/MozillaFoundation/movement-building/milestones/Surveillance%20Campaign

**Comment by edrushka** [comment]
Update:

#### Snippet
- [Snippet on staging] (http://scottdowne.github.io/eoy-snippets/eyeball-snippet/)
- [Snippet/eyeball ticket. (https://github.com/MozillaFoundation/movement-building/issues/44)
- build is 99% complete. Just need to swap in final copy
- we get this snippet beginning May 1
- Scott and Andrea reaching out to snippet team for review/testing

#### Interstitial
- design is complete
- build is nearing completion: http://scottdowne.github.io/surveillance-interstitial/public/

##### Interstitial MVPs 
- [ ] add the 2nd CTA [Details here.] (https://github.com/MozillaFoundation/movement-building/issues/41) 
- [ ] update the copy [Details here.] (https://github.com/MozillaFoundation/movement-building/issues/41) [Etherpad with final copy.] (https://etherpad.mozilla.org/interstitial-copy)
- [ ] add the link in the upper left. [Details here.] (https://github.com/MozillaFoundation/movement-building/issues/45)
- [ ] [QA] (https://github.com/MozillaFoundation/movement-building/issues/42)
- [ ] [Metrics] (https://github.com/MozillaFoundation/movement-building/issues/43)

**Comment by edrushka** [comment]
Update: We'll be ready to hand over to MoCo in a couple hours:

**Eyeball/snippet**
- Done. No changes.

**Interstitial**
- https://sendto.mozilla.org/page/content/surveillance-interstitial/
- Fix orphans (not a blocker to ship)
- Fix the last tiny design issues (not a blocker to ship)

**Metrics**
- Andrea will double check with Adam about tracking codes 
- documentation here: https://github.com/MozillaFoundation/movement-building/issues/43

**Mobile (P2, not shipping until next week)**
- icons don't work in Chrome
- Scott will finalize mobile early next week

**Shipping!**
- Andrea in on point to communicate with MoCo about flipping the switch

**Comment by edrushka** [comment]
Update:
This launched on Saturday. Great results so far :)
Scott is working on the mobile version [here] (https://github.com/MozillaFoundation/movement-building/issues/47#issuecomment-99260304) (almost done)
And Jess is working on the tile [here] (https://github.com/MozillaFoundation/movement-building/issues/33#issuecomment-99212245).

**Comment by edrushka** [comment]
Update: 
snippet is live
desktop is done
mobile is done
tile is done

To Do: 
Call congress tool

**Comment by OpenMatt** [comment]
Let's do a post-mortem re: process efficiencies for next time around

**Comment by OpenMatt** [comment]
status update?

**Comment by edrushka** [comment]
Closing. We can re-open if needed.
