### ISSUE TITLE
Make CRM work for MoFo (ongoing)

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#441]
MoFo has a number of existing requirements and opportunities relating to CRM (Constituent Relationship Mangement). This is master ticket to capture the main projects within this task, and to keep the work visible within the heartbeat planning process.

### Audience
This work should serve the needs of MoFo staff, in order to support their relationships with the wider community. 

### Success
* Org wide understanding of what CRM is
* MoFo CRM in place for all teams who need CRM capacity
* Existing known CRM requirements solved for
* New opportunities discussed / planned / filed

### Vision
Ongoing product and project management until this turns from a set of tasks into a well defined service within MoFo.

### Measurement
TBC per sub project. 

But generally by improving the efficiency and efficacy of how we manage our engagement with constituents.

### Roles
 * Phase: Ongoing
 * Driver: @edrushka
 * Decision Maker: @adamlofting 
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier: Many - will list per sub project

**Comment by adamlofting** [comment]
Currently filed sub-projects are:

- [ ]  Migrate CRM Services from BSD to Salesforce/Exact Target #439 
- [ ]  Setup Exact Target for use with all MoFo transactional emails #433

**Comment by OpenMatt** [comment]
Documentation and scope: http://wiki.webmaker.org/CRM

**Comment by OpenMatt** [comment]
@adamlofting : rolling over to next heartbeat

**Comment by adamlofting** [comment]
I've made this ticket a P2 as it's just for ongoing high-level tracking. And I've filed another Plan ticket for the first sub-project in the BSD migration: 

- [ ]  MoFo Hosted Donation Pages (+ new payment processor) #455

**Comment by adamlofting** [comment]
Closing this as we're sticking to more granular tasks (2 week commitments) in Heartbeat Planning.
