### ISSUE TITLE
Teach site design work for June 19th heartbeat

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#475]
- [x] Interim brand identity for Mozilla Clubs: https://github.com/mozilla/teach.webmaker.org/issues/933
- [ ] Iterate on Clubs page: https://github.com/mozilla/teach.webmaker.org/issues/858
- [ ] Design user profile editor and viewer: https://github.com/mozilla/teach.webmaker.org/issues/711
- [ ] Design badge illustrations for Club Captain and Regional Coordinator badges: https://github.com/mozilla/teach.webmaker.org/issues/996

**Comment by hannahkane** [comment]
I think the badge design system question above is for @cassiemc.

**Comment by cassiemc** [comment]
@hannahkane what / where are the existing guidelines?

**Comment by hannahkane** [comment]
Good question! I don't actually know. I remember seeing this my first week here: http://emilygoligoski.com/2014/05/07/introducing-mozilla-visual-templates-for-badge-issuers/

But I don't know if that was officially approved.

**Comment by cassiemc** [comment]
@hannahkane Hmmm. This is probably worth a conversation.

**Comment by hannahkane** [comment]
Removed User Profile design and badge design from this heartbeat, as other tickets + clean-up from last heartbeat are taking longer than expected + there's been some unexpected design work added. Flagging that more design resources are needed to stay on track for Q2 and into Q3.

**Comment by hannahkane** [comment]
Completed the Clubs identity and made a good start on the Clubs page revisions. Other two tickets will need to be in a later heartbeat. Closing to re-prioritize.
