### ISSUE TITLE
Teach site engineering work for June 19th heartbeat

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#476]
Note: this is the prioritized backlog that I'll be taking to the Teach team on Monday. I'm not sure if they'll commit to everything in the list.

- [ ] Implement Pledge workflow: https://github.com/mozilla/teach.webmaker.org/issues/978
- [x] Implement Maker Party promo on Teach
- [ ] Implement MP promo on  Webmaker: https://github.com/mozilla/teach.webmaker.org/issues/989 
- [ ] Add existing translated versions of teaching kits and event guides (**Question**: is it safe to translate the web lit map, or is that changing soon?)
- [x] Explore Discourse integration: https://github.com/mozilla/teach.webmaker.org/issues/997
- [x] Build Tools page
- [ ] add Tools and Discourse to main navigation: https://github.com/mozilla/teach.webmaker.org/issues/990 
- [ ] Create the concept of a "Regional Coordinator" user type: https://github.com/mozilla/teach.webmaker.org/issues/923
- [x] various bugs and enhancements

**Comment by chrislarry33** [comment]
Hold on this, some quick changes soon: 

Add existing translated versions of teaching kits and event guides (Question: is it safe to translate the web lit map, or is that changing soon?)

**Comment by hannahkane** [comment]
Didn't complete everything in this heartbeat, but closing to account for changing priorities.
