### ISSUE TITLE
Shipping Webmaker App - The little bits

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#479]
In preparation of shipping Webmaker app, we have a few boxes that need help ticking:

* [x] Figure out access to help@webmaker.org ( https://github.com/MozillaFoundation/mofo-devops/issues/101 )
* [ ] RRA & possibly sec-review for api.webmaker.org (https://github.com/mozilla/webmaker-android/issues/1837)
* [ ] Load-testing for api.webmaker.org ( https://github.com/mozilla/api.webmaker.org/issues/84 )
* [x] Load-testing for screenshot-service

**Comment by simonwex** [comment]
These various pieces are in-progress. I have work to finish them off, and will be spending time doing them today.

**Comment by OpenMatt** [comment]
@simonwex can we close?
