### ISSUE TITLE
Make a "Volunteer Job Description" page prototype

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#482]
### Better volunteer contribution on-ramps in Q3 ###
* GOAL: do a more systematic job of recruiting and spelling out the value to contributors, especially for a small number of key roles we need help with in Q3. 
*  STRATEGY: There's a blog post notes from Whistler meetings here: http://openmatt.org/2015/06/24/on-ramps/
* DELIVERABLE for this Heartbeat: a template and prototype "Volunteer Role Application Page." Something we can internally test with colleagues and existing community. With some draft copy and some potential onboarding workflow. Focused on Open Product Developers and Mozilla Clubs Regional Co-ordinators to start, then potentially expanding from there. 
* EARLY PROTOTYPES AND SPIT-BALLING: this Heartbeat is just about playing in the sandbox, not trying to ship anything. 
* ALL ARE WELCOME. Let's hack together. Please CC yourself if you're interested in participating!

## Phase 1
- [x] Scope the work for this Heartbeat
- [x] Write a blog post with a proposal for the approach we're going to take this Heartbeat
- [ ] Get feedback from the Participation Lab team (Lucy / George). Especially on how this might dovetail with https://www.mozilla.org/contribute/ plans, and where / how the data from applicants should flow.
- [ ] Get feedback from community testers
- [x] Draft some volunteer role descriptions http://etherpad.io/mozilla_volunteer_positions
- [x] Produce a sample volunteer page 
- [ ] Get feedback on it from the wider group
- [ ] Write a blog post with scope and next steps for Phase 2

## Roles for Phase 1
* Project Manager: @OpenMatt
* Decision-Maker (Learning Products): @secretrobotron / @thisandagain 
* Decision-Maker (Learning Networks): @thornet 
* Consulted / Informed / Co-experimenters: @LauraReynal @jgmac1106 @hannahkane @benrito @ldecoursy @cassiemc @acabunoc @HPaulJohnson
* Community Testers: @panaggio, Ina, current Regional Co-ordinators

**Comment by LauraReynal** [comment]
cc / @LauraReynal

**Comment by jgmac1106** [comment]
cc / @jgmac1106

**Comment by secretrobotron** [comment]
cc @secretrobotron

**Comment by ldecoursy** [comment]
cc @ldecoursy

**Comment by cassiemc** [comment]
me too! cc @cassiemc

**Comment by thornet** [comment]
count me in! cc @thornet

**Comment by secretrobotron** [comment]
Might be able to tap the playbook for some value props and role descriptions: https://docs.google.com/presentation/d/1ALd2o6Lo47T_0PRfbewTWOrsqN9fj2qjuKJ7pbJJ_-M

Since they're already quite involved and have contributed lots to the effort, can interview people like @panaggio and [Ina](https://twitter.com/kemiri). Should identify more (maybe 2 per locale that we've already touched — BD and KE as well as IDN and BR).

Note: Wrt to people involved, there's some overlap between "Open Product Developer" and RC.

**Comment by cassiemc** [comment]
One of the issues I am noticing as I try to onboard a UX contributor is that there is no one place to assess all the different ```needs-help``` bugs across the repos for our various projects. Ideally we have one searchable repo (or a tool that searches across repos) so that if a person doesn't know what project they'd like to help out with they can pore through a list on their own. Maybe that already exists? OR maybe it's the other way around – and we design a way for contributors to contact all the PMs to see where they might be most useful at any given moment. It is currently super hard to put a contributor on something meaningful without giving them a bunch of background info.

**Comment by OpenMatt** [comment]
* @secretrobotron the playbook was a goldmine for drafting some "Volunteer Role Descriptions" -- exactly what we needed. See what you think: http://etherpad.io/mozilla_volunteer_positions
* @secretrobotron : can you review and update the "Open Product Developer" description, in particular?
* @cassiemc : agreed that we a way to view "needs-help" tickets across all repos would be awesome. @ScottDowne do you know how to do that, by any chance?
* @thornet : can you flesh out the "Regional Co-ordinator" description in this etherpad? http://etherpad.io/mozilla_volunteer_positions

**Comment by alamanda** [comment]
@OpenMatt I noticed that my name has been mentioned here:) Please let me know how can I help with this plan! --Ina

**Comment by benrito** [comment]
Exciting. Per our discussion in that Weds meeting, the build-out for this should start from an understanding of contributor motivation and incentives. For a lot of folks this is more formal recognition.

Particularly in the Webmaker launch markets, contribution ought to be understood as a career development opportunity. Contributors want to be able to show potential employers that they’ve worked with an international non-profit, learned network collaboration skills, showed problem solving and leadership. And for us to provide some semi-formal recognition of this (LinkedIn recommendations, etc) 

Our meetings with community in Bangladesh this week definitely confirmed this; faces lit up and energy significantly increased when we discussed the concept of recognition.

Closely tied to this is the concept of staff mentorship. We need some structure for how we support and guide volunteers through individualized contribution, and not assume that there are one-size-fits-all roles. I.e., roles described in playbook and definitions of RC should probably be understood as starting points, but not rigid categories.

The Bangladesh community volunteered to help us sketch out a 2 pager of how they’d like to see it work. Already have some idea of potential contributor stories (“So-and-so helped set up a specialized Q/A pipeline for Webmaker in Bangladesh, so that the software worked well on local popular handsets”) 

@openmatt — we were going to make this a Mozilla Learning working group. Do you want to lead it? Paging @bhuvanshri, who can help define scope.

Also adding @cecilepompei, who has been studying "employability through participation in Mozilla.” She’s on her way to East Africa this week and can provide more perspective from community there.

**Comment by cecilepompei** [comment]
@OpenMatt  super interested to work on this and I agree, what is key and I keep saying as well is not to assume that we know what they want: they will tell us.
We heard letter of recommendations and linkedin references so far in India and Bangladesh

More to come!

**Comment by thornet** [comment]
Thanks, @OpenMatt! 

The Regional Coordinator role is detailed here: https://teach.etherpad.mozilla.org/clubs-rc

And outlined in your pad.

**Comment by OpenMatt** [comment]
^ @benrito @cecilepompei +1 totally agree -- sounds good. So let's try creating a prototype page "volunteer role description page" and intake form. Then we can kick the tires on it with you guys, revise the copy, get some feedback from some of our existing volunteers, etc. 
* If you guys have ideas for writing up / spelling out the value proposition / what volunteers want feel free to hack on copy here: http://etherpad.io/mozilla_volunteer_positions
* Thanks @thornet! Awesome.

**Comment by OpenMatt** [comment]
* @secretrobotron and I were talking yesterday about the volunteer job description template going something like:

### Volunteer Role Description Template (draft)
# **Volunteer role title** (e.g., "Mozilla Clubs Regional Co-ordinator," or "Mozilla Open Product Developer," etc.)
# Short description. (what it is + value prop in 2 / 3 sentences)
http://etherpad.io/mozilla_volunteer_positions
# Responsibilities (what they do)
# Skills (attributes for doing the work) 
# Value Proposition (what they get back from Mozilla)
* Now documented in the pad http://etherpad.io/mozilla_volunteer_positions

**Comment by thornet** [comment]
Regional Coordinator description now in webby form:
http://mozilla.github.io/learning-networks/clubs/regional-coordinator.html

On Thu, Jul 9, 2015 at 3:42 PM, OpenMatt <notifications@github.com> wrote:

>
>    - @secretrobotron <https://github.com/secretrobotron> and I were
>    talking yesterday about the volunteer job description template going
>    something like:
>
> Volunteer Role Description Template (draft) *Volunteer role title* (e.g.,
> "Mozilla Clubs Regional Co-ordinator," or "Mozilla Open Product Developer,"
> etc.) Short description. (what it is + value prop in 2 / 3 sentences)
>
> http://etherpad.io/mozilla_volunteer_positions
> Responsibilities (what they do) Skills (attributes for doing the work) Value
> Proposition (what they get back from Mozilla)
>
>    - Now documented in the pad
>    http://etherpad.io/mozilla_volunteer_positions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/plan/issues/482#issuecomment-119970505>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by OpenMatt** [comment]
* @thornet : I love this! exactly where I was hoping we could go next -- generate some sample "Volunteer Role Pages" we could test out with current volunteers and colleagues. 
* If others want to hack on something similar, you can fork / remix Michelle's page. 
* Or: @secretrobotron set up a repo here as well: https://github.com/secretrobotron/mofo-volunteering
* All you need to do is add an html file to the repo, and it will show up at https://secretrobotron.github.com/mofo-volunteering/<your-file-name>.html

**Comment by thornet** [comment]
cc @Saallen if we want to add these kinds of volunteer descriptions for Mozfest roles?

**Comment by Saallen** [comment]
@thornet - yes- I could do an overview and then breakout all the individual roles of the festival

**Comment by OpenMatt** [comment]
### "Open application"
* One of the things that's inspired about Michelle's approach is: the "application" process is "open." As part of the application process, it invites people to a) make a quick thing that shows why they would be a good fit for the role, and b) share it publicly with other existing members of the community
* You can see some examples here -- they're great: http://discourse.webmaker.org/category/clubs/stories 

Why I love this:
* less work for us. doesn't require us to build out a form or figure out how to hold applicant data, etc.
* immediate gratification. once the applicant shares their artifact (blog post, make, whatever), they can start getting immediate guidance and feedback from other community members. 
* embodies our open, maker-based spirit. 
* can be easily tailored to the specifics of each role.

**Comment by OpenMatt** [comment]
Automation Team's "commitment curve," for reference: http://ateam-bootcamp.readthedocs.org/en/latest/guide/curve.html

**Comment by bhuvanshri** [comment]
Got the page! Happy to help develop a scope for the working group. Based on my reading so far, here how I would re-frame the current scope - would love feedback:
- The audience for the work would be our volunteers as well as staff
- We have some idea about what our volunteers want w.r.t recognition
 - Data points available are currently restricted to India and Bangladesh
 - Need more input from a diverse set of volunteers (working hypothesis being that the needs would vary by region, at least)
 - Need to consult the Participation team
 - What do some other organizations do to recognize their volunteers (and staff) contributions?
 - What would be the logistical needs of doing something more than what we do now w.r.t. recognition?
- We haven't yet discussed "What do we do to enhance staff participation?"
- One of the outcomes is a template we use across the organization for volunteer opportunities available (prototype already slated to be delivered for this heartbeat)

Makes sense w.r.t the current scope?

**Comment by benrito** [comment]
Yes, great!

I agree that some thinking on how staff participate in this system would make this more effective. What structures are / may be needed? @thisandagain has lots of thoughts on the mentorship piece.

**Comment by cecilepompei** [comment]
A few more questions and comments:

 - Do we have a quick on-boarding process or set of docs for people that would do that?
 - template across the company that all teams can simply fill in sounds awesome - maybe start small and we scale once it works. Bangladesh is a good place from what we saw, participation team can help us figure out others.
 - working with @benrito with Bangladesh community on recognition - @bhuvanshri I will get in touch around organizing these feedbacks

**Comment by OpenMatt** [comment]
To clarify, we're trying to bite off a very small part of this to start. :) Scope feel like it's gotten a bit loose (which is my fault.) Here's what I think we're trying to get done by Friday, July 17:

* **The first step is: ship a prototype "volunteer job description page."** Starting with two key volunteer roles: "Open Product Developer" and "Regional Co-ordinator." 
** a draft Regional Co-ordinator prototype page is already completed and ready for feedback here: http://mozilla.github.io/learning-networks/clubs/regional-coordinator.html
** "Open Product Developer" has [http://etherpad.io/mozilla_volunteer_positions] (draft copy written here) -- but hasn't been turned into a page yet (@secretrobotron: could you do this this week?) 

* These pages will first and foremost: describe the role, and lay out the value proposition for volunteers. 
* They will also draft a suggested process for **how to apply**. Michelle takes a novel "open application" approach to this in her page that we should think about duplicating. 
* Once these prototype pages are done, we can test and get feedback on them. The copy, approach, HR / legal check, etc. Then improve them and hopefully aim to ship them next Heartbeat. 
* The result will also be a template we can potentially use for other roles as well. 
* All the other comments about on-boarding documents, mentorship, etc -- these are helpful, and we will need those things. And at the same time: we'll want to get a small piece of work done quickly, so we can make progress.

**Comment by OpenMatt** [comment]
### Next steps this week

* **Open Product Developer page.** @secretrobotron : do you think you could turn the draft copy we worked on into a prototype web page for "Open Product Developer", similar to (or forking) Michelle's?
* **Mentorship model**. @benrito @thisandagain @cecilepompei Do you have a theory of how mentorship / pairing should work for the Open Product Developer position? Want to write a draft proposal somewhere? like: etherpad.io/Open_Product_Developer_mentorship
* **On-boarding documentation.** @cecilepompei @secretrobotron @LauraReynal Do we have some grist / existing copy we could use to hammer out a quick and dirty: "How to be an Open Product Developer for Mozilla" wiki page?

**Comment by secretrobotron** [comment]
:+1: 
Is there any reason the page itself shouldn't have the information that would go on the wiki?

**Comment by OpenMatt** [comment]
@secretrobotron nope. but the supporting on-boarding docs don't necessarily need to be a blocker for shipping the role description page, I'd say. They can always get added whenever we have them.

**Comment by bhuvanshri** [comment]
With regards to on-boarding documentation, I believe @acabunoc and @kaythaney had been working on a common on-boarding curriculum / document that can be useful here too.

**Comment by cecilepompei** [comment]
On-boarding - went straight to the source and asked a few volunteers
(mentors and Reps) that confirmed that lack of on-boarding is a challenge
because people that want to get involved are not sure of how to do so.

The more experienced volunteers that mentor all new volunteers welcome our
initiative to work on this. We went through it in detail and they recommend
a package with:

   -  How does Bugzilla works
   - How do you file Bugs
   - Organizational structure: who do you ask at Mozilla when you have a
   question -- for example, Bobby added its name at the end of the job
   description and that is super helpful (say the volunteers)
   - SOP (standard operating procedures) on how to start contributing (more
   global than only open product developer but helps to know they want this)
   -  How to be part of the community internationally
   - Be assigned to a mentor

> I had built an on-boarding program for a new staff we had doing half
Regional Cooridnators and Webmaker - @openmatt - I will send it to you now
by email

Which brings us to mentorship topic:

   -  'open product developer" is a hard one because involves a lot of
   various tasks , more like a product manager - but I think everyone at
   Mozilla should mentor one or two volunteer worldwide
   - mentors should communicate to volunteers what are the crucial links to
   read through and focus on the importance of some of the links to learn how
   to participate (feedback from the community)
   - pairing could be a test to start with and we can ask in product team
   (since it is more product focus) who wants to get involved. The same way
   Michelle recruited some "staff organizers" to pair them with RC and test
   her pairing
   - extra note: we need a guide as well for mentors on how to support
   mentees in the future


On Mon, Jul 13, 2015 at 11:46 PM, Bhuvan Shrivastava <
notifications@github.com> wrote:

> With regards to on-boarding documentation, I believe @acabunoc
> <https://github.com/acabunoc> and @kaythaney
> <https://github.com/kaythaney> had been working on a common on-boarding
> curriculum / document that can be useful here too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/plan/issues/482#issuecomment-121052560>
> .
>



-- 
Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by cassiemc** [comment]
Throwing a link in for inspiration – a "book club" is an interesting way to think about folding contributors into a fairly complex system in a way that is both natural and fun. http://creative.mailchimp.com/book-club/ Could see @cecilepompei's proposed guides fitting into this format really well.

**Comment by chrislarry33** [comment]
Big +1 to looking at what @acabunoc and @kaythaney have already been working on and see what can work from that

**Comment by alamanda** [comment]
@OpenMatt I'm based in Jakarta, Indonesia and has been volunteering for Mozilla since 2011, before became ReMo last year. My skills and experiences are mostly related to organizing events and talking to people. Therefore, I feel like I can channel those toward Webmaker, other than helping other ReMo/FSA/Mozillians alike to organize events that will introduce Mozilla's projects as well as encouraging people to start contributing to Mozilla. 
During Maker Party period last year I organize and co-organize at least 3 events. Other ReMo in Indonesia practically did the same, or even more. I tend to concentrate on hands-on approach workshops when organizing events. However, I always make sure that we have 10-15 minutes introduction session called "Contributing to Mozilla", in which we project mozilla.org page to a big screen and guide participants to click 'get involved with mozilla today' button and see different areas anyone can contribute to. Based on my experience, some participants will get inspired, and then started to discuss the possibility of doing an event in their community/university/school. And that's how the ball keeps rolling. 
We got our budget for events mostly through the Reps Program. That's why I always feel that all Mozilla's projects are intertwined, that I don't have to differentiate whether I discuss about Webmaker or Firefox, or FirefoxOS in a more general events. 

This year, I started to be Regional Coordinator for Mozilla Club. Although it's a new role with different set of responsibilities, I decided to use the available platform so that I can start working with people I can trust, and having the advantage to get Captains from different cities in Indonesia right away. Since we started, we already have 6 clubs and two more are still in process of making in 6 different cities (hundreds of miles apart). I contacted FSA and Mozillians that show leadership capabilities, offered them the opportunity of having a regular 'space' to teach and learn. 

These Mozilla Club Captains have been proven to be reliable and resourceful, now that Indonesia is one of the focuses for Webmaker App Launching. We work closely with @secretrobotron to organise a bigger launch event and some smaller launch events, and more than a dozen school visits to attract media attention and foster general public to download the app and create fun projects with it. 

Related to the plan mentioned in this issue, I wonder if this plan will start a different platform from what's already available (Reps and FSA)? 

Last but not least, I have two opinions regarding recognition. First, I think Linkedin References and Letter of Recommendation is important for fresh graduates, or people like me, who has almost no technical qualifications, to prove that we have been part of a global technology community. Second, for programmers/developers/QA people etc. Once they've contributed for quite some time, they could simply share links (github, bugzilla) of their contribution to prospective employer, so that they can be assessed through their technical skills. I got the last input from fellow ReMo who's also a developer.

**Comment by cecilepompei** [comment]
here is a link for an on-boarding template for someone working on Clubs and
Webmaker:
https://docs.google.com/document/d/1RuWp4KRLgTCSXzOxe60-ndatqIX_auu93QxAVvYjBWE/edit

On Tue, Jul 14, 2015 at 5:36 AM, Dian Ina Mahendra <notifications@github.com
> wrote:

> @OpenMatt <https://github.com/OpenMatt> I'm based in Jakarta, Indonesia
> and has been volunteering for Mozilla since 2011, before became ReMo last
> year. My skills and experiences are mostly related to organizing events and
> talking to people. Therefore, I feel like I can channel those toward
> Webmaker, other than helping other ReMo/FSA/Mozillians alike to organize
> events that will introduce Mozilla's projects as well as encouraging people
> to start contributing to Mozilla.
> During Maker Party period last year I organize and co-organize at least 3
> events. Other ReMo in Indonesia practically did the same, or even more. I
> tend to concentrate on hands-on approach workshops when organizing events.
> However, I always make sure that we have 10-15 minutes introduction session
> called "Contributing to Mozilla", in which we project mozilla.org page to
> a big screen and guide participants to click 'get involved with mozilla
> today' button and see different areas anyone can contribute to. Based on my
> experience, some participants will get inspired, and then started to
> discuss the possibility of doing an event in their
> community/university/school. And that's how the ball keeps rolling.
> We got our budget for events mostly through the Reps Program. That's why I
> always feel that all Mozilla's projects are intertwined, that I don't have
> to differentiate whether I discuss about Webmaker or Firefox, or FirefoxOS
> in a more general events.
>
> This year, I started to be Regional Coordinator for Mozilla Club. Although
> it's a new role with different set of responsibilities, I decided to use
> the available platform so that I can start working with people I can trust,
> and having the advantage to get Captains from different cities in Indonesia
> right away. Since we started, we already have 6 clubs and two more are
> still in process of making in 6 different cities (hundreds of miles apart).
> I contacted FSA and Mozillians that show leadership capabilities, offered
> them the opportunity of having a regular 'space' to teach and learn.
>
> These Mozilla Club Captains have been proven to be reliable and
> resourceful, now that Indonesia is one of the focuses for Webmaker App
> Launching. We work closely with @secretrobotron
> <https://github.com/secretrobotron> to organise a bigger launch event and
> some smaller launch events, and more than a dozen school visits to attract
> media attention and foster general public to download the app and create
> fun projects with it.
>
> Related to the plan mentioned in this issue, I wonder if this plan will
> start a different platform from what's already available (Reps and FSA)?
>
> Last but not least, I have two opinions regarding recognition. First, I
> think Linkedin References and Letter of Recommendation is important for
> fresh graduates, or people like me, who has almost no technical
> qualifications, to prove that we have been part of a global technology
> community. Second, for programmers/developers/QA people etc. Once they've
> contributed for quite some time, they could simply share links (github,
> bugzilla) of their contribution to prospective employer, so that they can
> be assessed through their technical skills. I got the last input from
> fellow ReMo who's also a developer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/plan/issues/482#issuecomment-121115240>
> .
>



-- 
Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by OpenMatt** [comment]
@alamanda : thank you for this! Hugely helpful. I'm going to try and summarize some of what you wrote about the RC piece in particular.  

### Becoming an RC
* As a ReMo, you decided to become a Regional Coordinator for Mozilla Clubs because it: 
   * allows you to work with people you trust
   * provides a chance to get Captains from different cities right away. 
* You now have 6 active clubs, with more coming, in 6 different cities
* You recruited Club Captains from within the existing Mozilla community. Focusing on: Firefox Student Ambassadors and Mozillians that show leadership capabilities.
* The main value you offered them to start a Club was: having a regular 'space' to teach and learn.

### Overlap with Webmaker app 
* The fact that Indonesia was a focus for the Webmaker App launch helped your efforts. e.g., there's overlap between our Clubs work and our Regional Co-ordinator work.
* You're working with @secretrobotron to organize follow-up Webmaker launch events at schools, to generate media attention, encourage downloads, and create fun projects with it.
* ( @alamanda : do you think these events could also help seed Clubs / recruit Club Captains as well? )

### Recognition / Value Proposition 
* Linked-In References and Letter of Recommendation are important.
* Especially for volunteers who do not have formal technical qualifications, to prove they've been a part of a global technology community
* For programmers/developers/QA people, they are also able to share links (github, bugzilla) of their work to prospective employers, so they can be assessed on their technical skills. 

### Questions
* are we starting a different platform from what already exists with (Mozilla Reps and Firefox Student Ambassadors? How are we showing up there?

**Comment by acabunoc** [comment]
Hi all,

Yes, we've been working on an common on-boarding curriculum for fellows and community leaders.

This is very much a work in progress right now:
http://mozillascience.github.io/leadership-training/index.html

Would love to help out / hear your feedback!

**Comment by OpenMatt** [comment]
@cecilepompei @acabunoc : this is great -- I'm going to file a new ticket to focus specifically on the on-boarding process here: https://github.com/MozillaFoundation/plan/issues/495
* We can use this ticket to ship the volunteer description pages. And use that one to focus on the on-boarding piece.

**Comment by secretrobotron** [comment]
Draft pages are up in the mofo-volunteering repo:
* http://secretrobotron.github.io/mofo-volunteering/open-product-developer.html
* http://secretrobotron.github.io/mofo-volunteering/regional-coordinator.html

Obviously unfinished.

**Comment by alamanda** [comment]
@OpenMatt About becoming an RC, I was offered to be RC, and not applied. Once I became RC, I think the easiest way to recruit Club Captains is by approaching FSA and Mozillians that are already a leader in their own communities. Those are people I can trust because I already know them, and had worked together with them before. And because they're living in different cities, by recruiting them, I already have several Club Captains in Jakarta, Bandung, Makassar, Semarang, Madura and Surabaya. 

To answer your question: Yes, I think the events we're doing for Webmaker App Launch could help seed clubs/recruit Club Captains. I already have a teacher who eager to start a Mozilla Club for his students, after we discussed about a Webmaker App workshop in his school (upcoming in August). 

I hope my explanation helps:)

**Comment by OpenMatt** [comment]
@secretrobotron : thanks for getting these prototypes created. Can you demo them today? 
* I can take a pass at editing copy, etc. on Monday. Then we can be ready for more feedback and testing on them in next Heartbeat.

**Comment by cecilepompei** [comment]
What are our metrics and plan to test and learn from this experiment?

On Fri, Jul 17, 2015 at 4:46 PM, OpenMatt <notifications@github.com> wrote:

> @secretrobotron <https://github.com/secretrobotron> : thanks for getting
> these prototypes created. Can you demo them today?
>
>    - I can take a pass at editing copy, etc. on Monday. Then we can be
>    ready for more feedback and testing on them in next Heartbeat.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/plan/issues/482#issuecomment-122278432>
> .
>



-- 
Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by OpenMatt** [comment]
This work fell by the wayside because of 3-year planning. I'm going to punt it to late Sep.

**Comment by cassiemc** [comment]
@vazquez Wrote a description for an open source design volunteer position – would love anyone's thoughts about how this process could go! https://github.com/MozillaFoundation/Design/issues/50#issuecomment-137548850

Specifically, I'm interested in knowing – where do we post such a description? What does the application process look like? (what is the volunteer criteria, who assesses the criteria, how does this volunteer get onboarded)

**Comment by ScottDowne** [comment]
@cassiemc Sorry for the delay, I missed your initial mention ages ago, but to find all issue with the "needs-help" label, you can do that here: http://build.webmaker.org/issues

That by default searches all our repos. Change the drop down to label, and type in "needs-help" or the label you want to search by. It should auto-complete based on labels we have used.

**Comment by OpenMatt** [comment]
Moving to Oct 23 Heartbeat. @secretrobotron and I are hoping to get something done on this for MozFest. 3-year plan is eating up all my time right now.

**Comment by ldecoursy** [comment]
@OpenMatt

**Comment by cassiemc** [comment]
@OpenMatt status update?

**Comment by cassiemc** [comment]
I'll move this to Jan 15 as I believe @OpenMatt is off until the next heartbeat.
