### ISSUE TITLE
Add analytics tracking to Teach site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#500]
We need to collect some data on user behavior.

Relevant tickets:
 - [x] https://github.com/mozilla/teach.webmaker.org/issues/1110
 - [x] https://github.com/mozilla/teach.webmaker.org/issues/1109
 - [x] https://github.com/mozilla/teach.webmaker.org/issues/1112

**Comment by hannahkane** [comment]
In progress

**Comment by OpenMatt** [comment]
@hannahkane roll over to next milestone?

**Comment by hannahkane** [comment]
Yes, I believe there's an outstanding PR on this one.

**Comment by hannahkane** [comment]
Bam.
