### ISSUE TITLE
Prep new Thimble for launch

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#530]
This work includes:
 - [x] QA (everyone!) see https://github.com/mozilla/thimble.webmaker.org/issues/807
 - [x] Bug fixing (Seneca team) see https://github.com/mozilla/thimble.webmaker.org/labels/P1
 - [x] Marketing deliverables see https://github.com/MozillaFoundation/plan/issues/518
 - [x] Prepare to host two versions during beta period see https://github.com/MozillaFoundation/plan/issues/519
 - [x] DevOps https://github.com/MozillaFoundation/mofo-devops/issues/157

### DARCI ###
Driver: Hannah
Engineers: CDOT team for Thimble/Brackets work; @mmmavis for BSD template
Designers: @flukeout @sabrinang 
Marketing/Comms: @HPaulJohnson @KevZawacki 
Consulted: @cassiemc @simonwex @ldecoursy 
Devops: TBD

**Comment by hannahkane** [comment]
Flag for TPS: mostly want to flag #519 and make sure we'll have Devops support

**Comment by OpenMatt** [comment]
status?

**Comment by hannahkane** [comment]
Prepped. Launched.
