### ISSUE TITLE
MozFest work!

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#539]
For this heartbeat, hoping to tackle:
 - [x] Copy edits (https://github.com/mozilla/2015.mozillafestival.org/issues/157)
 - [x] Change header on 2014 site to point users to 2015 site (https://github.com/mozilla/2015.mozillafestival.org/issues/168)
 - [ ] Add Sitelinks to improve SEO (https://github.com/mozilla/2015.mozillafestival.org/issues/169)
 - [x] Provide no-build solution for session proposal reviewers to manage their work
 - [x] shut down session submissions, including messaging
 - [x] Export session submissions from google form to github repo (https://github.com/mozilla/teach.webmaker.org/issues/1235)

**Comment by edrushka** [comment]
@simonwex @davidascher Do you know which dev is working on this this heartbeat?

**Comment by hannahkane** [comment]
@mmmavis and @ScottDowne are working on the first item in the list. @Saallen and I are meeting next Monday to tackle the fourth item.

Second and third item need a developer. We have a contributor who might be able to do it, though. I'll follow up shortly.

**Comment by mmmavis** [comment]
curious - isn't 2014 site archived already: http://2014.mozillafestival.org/

**Comment by hannahkane** [comment]
I'll be honest, I don't know exactly what it means to "archive," but I think the desired state is for the 2014 site to not be the first google result when you search for "MozFest," or perhaps to not appear at all.

**Comment by edrushka** [comment]
I believe @jbuck told me a couple weeks ago that the 2015 site was the first search result.

**Comment by hannahkane** [comment]
2014 is first for me. Is that just me?

**Comment by ScottDowne** [comment]
2014 is first for me too.

**Comment by hannahkane** [comment]
I don't have a deep understanding of PageRank, but I think if you search for "MozFest," 2014 comes up first, and if you search for "Mozilla Festival," 2015 comes up first.

However, upon investigating further, I think there's a different solution we could employ. The 2014 homepage is actually pretty confusing right now, since the first thing the user will see is a prominent banner advertising the 2015 event. It's easy to see how people would mistake this for the 2015 site. We should replace that header with something less misleading, and provide a link to the 2015 site. Will file a separate ticket for that.

**Comment by hannahkane** [comment]
Added links to new tickets to this ticket's description

**Comment by Saallen** [comment]
+1 to hannahs suggestion. We still have folks signing up for updates on the old site.

**Comment by hannahkane** [comment]
Experimenting with exporting all session proposals into Github as a solution for session reviewers. So far, so good.

**Comment by simonwex** [comment]
Is there a reason not to redirect the 2014 site to 2015? In general, having the year in the domain name is bad news for our Google sauce.

**Comment by davidascher** [comment]
I think we want to focus the google juice for the site-of-the-year, but to
have a record for older sites.  This doesn't seem super hard though =)

**Comment by OpenMatt** [comment]
@hannahkane rolling into next heartbeat? or closing out?

**Comment by OpenMatt** [comment]
@hannahkane status?

**Comment by hannahkane** [comment]
almost done
