### ISSUE TITLE
Release new Goggles

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#554]
TODOs:
 - [x] finish rewriting the goggles login system to use id.wmo (https://github.com/mozilla/teach.webmaker.org/issues/1220)
 - [x] [design new homepage](https://github.com/mozilla/teach.mozilla.org/issues/1298)
 - [ ] [provide access to new projects](https://github.com/mozilla/teach.mozilla.org/issues/1223)
 - [x] [favicon and bookmark bar icon](https://github.com/mozilla/teach.mozilla.org/issues/1317)
 - [x] [FTU page](https://github.com/mozilla/teach.mozilla.org/issues/1310)
 - [x] [FTU activity](https://github.com/mozilla/teach.mozilla.org/issues/1324)
 - [x] [create tutorial gifs for homepage](https://github.com/mozilla/teach.mozilla.org/issues/1232)

**Comment by hannahkane** [comment]
Lots of progress this heartbeat, but this work will span the next heartbeat as well.

**Comment by hannahkane** [comment]
For those interested in the Goggles homepage design, see https://github.com/mozilla/teach.mozilla.org/issues/1298

**Comment by hannahkane** [comment]
Design is wrapping up, but add'l tickets have been added, and work will continue into the next heartbeat.

**Comment by jgmac1106** [comment]
Is there a rough timeline? Should I avoid signing people up to use Goggle's
until the milestone is complete?

**Comment by hannahkane** [comment]
@jgmac1106 - don't want to promise anything specific in terms of a timeline, but people can still use [Goggles](https://webmaker.org/en-US/goggles) in the meantime.

**Comment by jgmac1106** [comment]
Thanks, didn't need the promise.  Just wanted to make sure there wasn't
going to be a gap.

Goggles is essential to my credibility unit I teach.

Thanks for letting me know.

**Comment by hannahkane** [comment]
Ongoing work...moving to next heartbeat.

**Comment by hannahkane** [comment]
Tons of progress (updated checklist in first comment). Will test out at MozFest.

**Comment by hannahkane** [comment]
Got a lot of feedback at MozFest. Need to discuss and decide if we have new steps to complete before releasing. Moving to next heartbeat.

**Comment by OpenMatt** [comment]
* final piece left to do: browser detection
* @Pomax says he will finish by end of week -- @Pomax can you update?

**Comment by Pomax** [comment]
browser detection has been added in (at least on the staging server) including mobile detection to warn users that goggles is a desktop experience. The only checkbox we don't have ticked off at this point is the gallery aspect

**Comment by xmatthewx** [comment]
Is the gallery experience required to launch the tool? Or could that be added later?

**Comment by hannahkane** [comment]
Can happen later, IMO.

**Comment by hannahkane** [comment]
Pushing to new year, because we'll get the Moco security review on the 4th of January.

**Comment by hannahkane** [comment]
RRA is now happening on the 15th, so moving this to the next heartbeat.

**Comment by hannahkane** [comment]
@Pomax - are we good to close this?

**Comment by Pomax** [comment]
a bit late, but yes. There is a followup around making users aware that goggles have moved, by making the old goggles file throw up a dismissible dialog, but that should not hold up this issue.
