### ISSUE TITLE
Deprecate Webmaker Sites And services

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/plan#569]
Checklist based on https://github.com/MozillaFoundation/mofo-devops/issues/182 and https://github.com/MozillaFoundation/mofo-devops/issues/189

1. Deprecation Preparation
  - [x] [Create & deploy deprecation page](https://github.com/MozillaFoundation/mofo-devops/issues/187)
2. Webmaker Profile
  - [x] Disable access to Profile via webmaker.org configuration option
  - [ ] [Shut down Webmaker Profile infrastruture](https://github.com/MozillaFoundation/mofo-devops/issues/184)
    - **blocked** due to running on shared infrastructure. Shared with Goggles, Thimble, and Popcorn. Maybe we move Goggles and Thimble over to Heroku?
  - [ ] Modify Github repo and readme to note that it's been decommissioned
3. Webmaker Events
  - [ ] Change events.webmaker.org to point at deprecation page
  - [ ] Remove events-api.webmaker.org from DNS
  - [ ] [Shut down Webmaker Events infrastruture](https://github.com/MozillaFoundation/mofo-devops/issues/185)
  - [ ] Modify Github repo and readme to note that it's been decommissioned
4. Webmaker Welcome
  - [ ] Change welcome.webmaker.org to point at deprecation page
  - [ ] [Shut down Webmaker Welcome infrastruture](https://github.com/MozillaFoundation/mofo-devops/issues/190)
  - [ ] Modify Github repo and readme to note that it's been decommissioned
5. Teach
  - [ ] Rename repo to "teach.mozilla.org"
  - [ ] Implement `/me` page on Teach that fetches Makes from MakeAPI
6. makes.org / make-valet
  - [ ] **blocked** Modify [make details bar](https://www.dropbox.com/s/r76k04xuvk2jomc/Screenshot%202015-09-16%2014.10.08.png?dl=0) to be rendered by the make-valet or remove it entirely. Who decides this?
7. beta.webmaker.org
  - [ ] Add redirect from `/me` to `teach.mozilla.org/me`
  - [ ] Change webmaker.org to point at beta.webmaker.org. Keep beta.webmaker.org DNS around since it's been used for awhile.
  - [ ] Add redirect for beta.webmaker.org to webmaker.org
8. webmaker.org
  - [ ] Shut down webmaker.org infrastructure
  - [ ] Modify Github repo and readme to note that it's been decommissioned
9. Appmaker
  - [ ] Disable saving new content
  - [ ] The saved makes link directly to apps.webmaker.org so we should upload the static content of apps.webmaker.org to webmak.es and modify the `<base>` tag appropriately
  - [ ] Change apps.webmaker.org to point at deprecation page
  - [ ] Shut down Appmaker infrastructure
  - [ ] Modify Github repo and readme to note that it's been decommissioned
10. Popcorn
  - [ ] Disable saving new content
  - [ ] The saved makes link directly to popcorn.webmaker.org so we should upload the static content of popcorn.webmaker.org to makes.org and modify the `<base>` tag
  - [ ] Change popcorn.webmaker.org to point at deprecation page
  - [ ] Shut down Popcorn infrastructure
  - [ ] Modify Github repo and readme to note that it's been decommissioned
11. Goggles
  - [ ] **blocked** Wait for Pomax to refactor Goggles with id and publish
  - [ ] Disable saving new content
  - [ ] Modify the script living on goggles.webmaker.org to redirect to a page instructing people how to install the "new" goggles bookmarklet.
  - [ ] Change goggles.webmaker.org to point at deprecation page
  - [ ] Shut down Goggles infrastructure
  - [ ] Modify Github repo and readme to note that it's been decommissioned
12. Thimble
  - [ ] Rename repo to `thimble.mozilla.org`
  - [ ] Rename `master` branch to `classic`
  - [ ] Rename `bramble` branch to `master`
  - [ ] **blocked** Wait for Thimble team to add l10n to bramble
  - [ ] Disable saving new content
  - [ ] Figure out a way of importing thimble content into bramble. I'm personally a fan of running a bulk import with redirects or have redirects run the import step within the users browser. Either way is fine!
  - [ ] Change thimble.webmaker.org to point at deprecation page
  - [ ] Shut down Thimble infrastructure
13. makes.org / make-valet
  - [ ] Convert all of the make metadata within makeapi to static data that the make-valet can use somehow
  - [ ] Convert the "make details" iframe to be rendered with the now-static metadata
14. Teach
  - [ ] Refactor /me to use static make metadata on makes.org
15. MakeAPI
  - [ ] Remove makeapi.webmaker.org from DNS
  - [ ] Shut down MakeAPI infrastructure
  - [ ] Modify Github repo and readme to note that it's been decommissioned
16. id.webmaker.org
  - [ ] Implement user database running within id.wm.o, instead of depending on login.wm.o
  - [ ] Implement a user settings page on id.wm.o
17. login.webmaker.org
  - [ ] Remove login.webmaker.org from DNS
  - [ ] Shut down Login infrastructure
  - [ ] Modify Github repo and readme to note that it's been decommissioned

**Comment by xmatthewx** [comment]
Excellent. So great to see this work in motion with so much clarity. 

Notify @HPaulJohnson if we need to communicate anything different to users. Right now, that doesn't seem like the case. 

cc @hannahkane

**Comment by hannahkane** [comment]
+1 excellent to have this comprehensive list!

**Comment by cadecairos** [comment]
Just though of another thing we need to make a decision on while we deprecate things.

Each make type generates a default thumbnail specific to the tool. 

For appmaker it is `https://apps.webmaker.org/images/app-icon.png`
For thimble it is `https://webmaker.org/img/thumbs/thimble-grey.png`
For popcorn maker it is `https://popcorn.webmaker.org/resources/icons/fb-logo.png`
Goggles doesn't seem to even create a thumbnail...

The decision we have to make is how to not break these links for the large number of makes that use them, or we figure out how to replace them.

cc/ @simonwex @hannahkane

**Comment by xmatthewx** [comment]
Good catch. We should figure out how valuable those old thumbnails are before we make a plan to rescue them.

**Comment by hannahkane** [comment]
I'm not sure I understand. Why wouldn't we keep these?

**Comment by xmatthewx** [comment]
If it requires many hours of work, then it might not be worth it for projects on retired tools. Will there still be an explore experience for popcorn maker? Or will these projects just be listed in a user's own list of projects? 

Just my 2¢.

**Comment by cadecairos** [comment]
As far as I know, the only way to access old makes will be through the soon to be completed `teach.mozilla.org/me` page. I thought `popcorn.webmaker.org` was going to be shut down?

**Comment by hannahkane** [comment]
@cadecairos - you are correct. Do we not need those thumbnails on the teach.mozilla.org/me page? If not then I agree we can scrap them.

**Comment by hannahkane** [comment]
Moving to Jan milestone, since this is still in progress

**Comment by cadecairos** [comment]
Here's a quick update:

We're waiting on a RRA (Rapid Risk Assessment) for Goggles, so that Moco will be okay with updating DNS for goggles.mozilla.org (https://bugzilla.mozilla.org/show_bug.cgi?id=1230666) It should be happening the week of Jan 4.

Once that's done, we'll be able to move beta.webmaker.org to webmaker.org.

We also still need to work on shutting down appmaker.

**Comment by OpenMatt** [comment]
@cadecairos update?

**Comment by cadecairos** [comment]
@OpenMatt http://www.mofo.build points to the app, but we're going to need SSL for that domain.

@simonwex How should we get that?

**Comment by xmatthewx** [comment]
Work continues as p2

**Comment by Pomax** [comment]
techical nit: goggles isn't getting decommissioned, only the webmaker.org/goggles location is, so for point 11 we need a bit to inform currrent users to go use the new bookmark on goggles.mozilla.org instead

**Comment by simonwex** [comment]
This is ongoing work. I'm going to track this in this repo slightly differently in the future as a standing devops ticket.

**Comment by hannahkane** [comment]
@simonwex - is this ticket still useful? Is it up to date?
