### ISSUE TITLE
Curriculum updates

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#582]
- [x] Add [Back to School kit](https://github.com/mozilla/teach.mozilla.org/issues/1290) to teach.mozilla.org.
- [x] Add [Webmaper app modules](https://github.com/mozilla/teach.mozilla.org/issues/1264) to teach.mozilla.org. 
- [x] Add expanded [Privacy kit](https://github.com/mozilla/teach.mozilla.org/issues/1353) to teach.mozilla.org
- [x] [Improve curriculum queue page](https://github.com/mozilla/teach.mozilla.org/issues/1364) (partially done)
- [x] and [link to it](https://github.com/mozilla/teach.mozilla.org/issues/1363)

cc @chadsansing @hannahkane

**Comment by hannahkane** [comment]
Are these being framed as part of the "tiered" Clubs model? Wondering if we need to offer a design solution that clarifies to Club Captains which modules we recommend they use for their Clubs.

**Comment by ldecoursy** [comment]
I like that idea @hannahkane, as currently it's hard to distinguish between the modules vs. individual activities. Was thinking first step would just be to add them to /activities - think @chadsansing has already filed tix for that?

**Comment by chadsansing** [comment]
See also https://github.com/mozilla/learning-networks/issues/250.

I'm hoping we can inform our solution/labels with the rubric & guidelines work going on, but I need more testers. Will ask for more help on team call this week.

**Comment by chadsansing** [comment]
The Webmaker ticket lives at https://github.com/mozilla/teach.mozilla.org/issues/1264.

**Comment by hannahkane** [comment]
@chadsansing - would it be alright if we saved this ticket for the next heartbeat? We're trying to identify tickets that might be good for participants of Grace Hopper Day on the 13th. Emma Irwin has asked if she can draw from Teach, and we thought this might  be a good ticket for them to take on.

**Comment by chadsansing** [comment]
Sounds right -

**Comment by hannahkane** [comment]
Hoping the Privacy Kit lands tomorrow. Others will likely be next heartbeat.

**Comment by hannahkane** [comment]
Back to School Kit and Privacy are done. Keeping this ticket open to track the other work.

**Comment by chadsansing** [comment]
+1000 & thanks all around.

**Comment by hannahkane** [comment]
Still working on the open items.

**Comment by hannahkane** [comment]
A casualty of the post-MozFest PTO phenomenon. Moving to next heartbeat.

**Comment by OpenMatt** [comment]
@hannahkane moved to this heartbeat + updated deliverables list in first comment

**Comment by ldecoursy** [comment]
@hannahkane I think we can check off all items listed in the first comment and close this - agree?

**Comment by hannahkane** [comment]
Yup.
