### ISSUE TITLE
Collect & share learnings from all design audits

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#685]
There are currently three design audits I'm aware of (Moco, Mofo, Teach), and this issue is about either completing those tasks or in the case of Moco, getting an update. In this process we will figure out how to share learnings from these audits and begin applying them across projects.

- [x] MVP Teach site style guide – https://github.com/mozilla/teach.mozilla.org/issues/1483 @sabrinang owns
- [x] identify audiences/personas – @sabrinang to own as part of the IA mapping exercise #661
- [x] mofo audit – https://github.com/MozillaFoundation/Design/issues/94 – @kristinashu owns
- [x] google deck: recommendations for what sites should remain, be combined or be eliminated – @kristinashu and @cassiemc

@cassiemc is speaking with Tim Murray to get an update on the Moco brand audit. @kristinashu and @sabrinang are also continuing to work on implementing the Teach site audit – https://github.com/mozilla/teach.mozilla.org/labels/design%20audit

Related: https://github.com/mozilla/teach.mozilla.org/issues/1384#issuecomment-164578153

**Comment by cassiemc** [comment]
@sabrinang is working on putting together a first go at the Teach site brand guidelines. This will have a knock on affect for the other audits, but I will need resource to help drive those to completion. Thinking @kristinashu will be able to help.

**Comment by cassiemc** [comment]
Kickoff scheduled for tomorrow. Will be collecting notes here: http://etherpad.io/brandauditskickoff

**Comment by cassiemc** [comment]
At the kickoff, @kristinashu @lovegushwa and @sabrinang and I agreed on an appropriate scope which I'll add to the first comment on this issue. Mostly we agreed that the outcomes are so based on the audit work that this task will be less overwhelming if it is phased, and that this current phase 1 should be about understanding all our various properties, drawing relationships between them, and surfacing problems. In a following heartbeat we will look more closely at proposing solutions.

**Comment by cassiemc** [comment]
Updating the milestone. The Mofo audit and teach audit are just finishing this heartbeat and would like some time to thoughtfully approach how to share the findings.

**Comment by cassiemc** [comment]
**Next step:** 
- [ ] fill out the gaps in [this document](https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=2008361845 ), an evolution of the Comms inventory doc (second tab).

This is basically a repetition of the [visual design audit here](https://docs.google.com/presentation/d/13v_Rr2ypxscqSZWksLAzc5TZ8NRy0MuGSP9yK-FEKFo/edit#slide=id.g10987373c5_0_222), but synthesized to a one-pager so it's easier to plan next steps and understand the impact of proposed changes. 

*Note* that the purple 'Impact of Change on Audience' section can be covered by https://github.com/MozillaFoundation/plan/issues/680 if we're unable to complete that section. I'm also going to track a few subtasks in the Design repo under the audit label: https://github.com/MozillaFoundation/Design/labels/audit

**Comment by cassiemc** [comment]
I think this work is coming along swimmingly and is already being applied in excellent ways in the IA work and CMS applications, but might still be too soon to share solid results w/ everyone. May start circulating with a small group next week. Pushing this out a milestone since I am also over-committed this heartbeat.
