### ISSUE TITLE
Finalize Web Lit Map 2.0 design

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#707]
Relevant tickets are:
 - [ ] [Update whitepaper](https://github.com/mozilla/teach.mozilla.org/issues/1600) – @anmechung and @Pomax 
 - [ ] [Finalize map design](https://github.com/mozilla/teach.mozilla.org/issues/1601)
 - [x] [Finalize copy](https://github.com/mozilla/teach.mozilla.org/issues/1602) – @anmechung 
 - [ ] [Update wireframes](https://github.com/mozilla/teach.mozilla.org/issues/1603)

I strongly urge us to finalize all copy/design work during the Feb 12th heartbeat, so that we can implement in the following heartbeat. This will require final copy EARLY in the heartbeat. @anmechung - is that doable?

**Comment by anmechung** [comment]
@hannahkane yes!  I can finalize copy by next week.

**Comment by hannahkane** [comment]
Copy is done. w00t! Good progress on map design as well.

**Comment by hannahkane** [comment]
The only part I'm worried about here is updating the whitepaper. Need more info from @anmechung about whether design and dev resources are needed.

**Comment by anmechung** [comment]
@hannahkane and I discussed, minimal/no design and dev resources needed as using existing designs per @sabrinang suggestion
