### ISSUE TITLE
Create & execute internal communications strategy for 2020 business plan

### ISSUE THREAD

**Issue by samanthaburton** [MozillaFoundation/plan#729]
**Full plan here:** https://docs.google.com/document/d/1fyNVt6gW-qt2VU6eovOBR0fkCisS2PmG-8g3VDIPROo/

D - Mark
A - Sam
R - Sam, Angela, Kevin, Paul
C - Chris, Lainie, Sara, Andrea, Cassie, Simon, Ben, Mark... likely others! 
I - all MoFo, MoCo close collaborators

**Objective (what is success by May 2016?)**
If we have successfully communicated a compelling 2020 Mozilla Foundation strategy, the broader MLN community & key supporters will have a clear understanding of what we’re doing and how to get involved.

To achieve this, we also need to ensure:
- MoCo & MoFo Leadership and MoFo board consistently use the language in Mozilla’s 2020 strategy to describe our work and priorities
- MoFo staff and key MLN members are confident in the 2020 Strategy, believe in the goals and approach, and understand their role in achieving it.

_Long-term: _Eventually, Mozilla is recognized as a diverse, global network of leaders protecting the open web and the boldest, loudest, most effective advocates for the internet by [target audience(s) Mozilla leadership, Mozilla staff, MLN members, peers, media

**Within next 2 weeks (by Feb 26)**
- [x] Core team kickoff with @samanthaburton @aplohman @KevZawacki @HPaulJohnson 
- [x] Run a baseline survey re: needs and materials - https://github.com/MozillaFoundation/strategy/issues/82
- [ ] Create canonical definitions for each of the leadership "tiers" - https://github.com/MozillaFoundation/strategy/issues/76
- [ ] Craft key messages for Privacy, Inclusion, Web literacy  - https://github.com/MozillaFoundation/strategy/issues/75
- [x] Define how MoFo strategy connects with the whole of Mozilla - https://github.com/MozillaFoundation/strategy/issues/74
- [x] Document how Advocacy and Leadership connect - https://github.com/MozillaFoundation/strategy/issues/73
- [ ] Create elevator pitch - https://github.com/MozillaFoundation/strategy/issues/68
- [ ] Define Mozilla Foundation's key differentiators - https://github.com/MozillaFoundation/strategy/issues/67
- [ ] Create an updated "how to get involved" page - https://github.com/MozillaFoundation/strategy/issues/70

**Comment by hannahkane** [comment]
Wondering if this ticket can be updated. I think some of these things have happened! (i.e. baseline survey).

@samanthaburton - also wondering if I can move this to the June 3 heartbeat, only because that corresponds to our two-week heartbeat schedule. We can put "May 31st" in the title of the ticket if that's the actual deadline.

**Comment by samanthaburton** [comment]
Thanks for the nudge @hannahkane! Updating now. And please feel free to move to the June 3 heartbeat - the deadline is flexible, especially as parts of the work will be transitioned to our new internal comms hire!

**Comment by hannahkane** [comment]
Hey @samanthaburton - should we move this into an upcoming heartbeat? What's most useful to you?

**Comment by samanthaburton** [comment]
I'm talking next steps with @KevZawacki and @Lottarao in London - can we update you after that?

**Comment by hannahkane** [comment]
Sure. I'll just move it into the current heartbeat for now.

**Comment by hannahkane** [comment]
Moving this out of July 1 heartbeat.

**Comment by hannahkane** [comment]
This ticket hasn't been touched in a year, so closing
