### ISSUE TITLE
Science Refresh: Research prep

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#739]
The Science Refresh is a multi-heartbeat project, but the current milestone is focused on preparing for a user research study, including creating some assets that we can test.

This work includes:
 - [x] [Draft a user research plan](https://github.com/mozillascience/site/issues/81)
 - [x] [Create IA proposals](https://github.com/mozillascience/site/issues/84)
 - [x] [Brainstorm homepage content and verbiage](https://github.com/mozillascience/site/issues/86)
 - [x] [Homepage wireframes](https://github.com/mozillascience/site/issues/87)

### DARCI
Driver: @hannahkane
A: ?
R: @kristinashu @my-le 
C: @acabunoc @cassiemc @kaythaney @zee-moz @stephwright @auremoser
I: @simonwex

**Comment by hannahkane** [comment]
During this heartbeat we drafted a user research plan, drafted several possible variations for the site IA, began brainstorming homepage copy, and created a first round of homepage wireframes.

We can close this ticket now, and open a new one for the next heartbeat where we'll implement the first phase of the user research plan and use the results to inform the overarching IA and the homepage copy and design.
