### ISSUE TITLE
Science Site: user research, analytics, IA, homepage copy and wireframes

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#744]
#### DARCI
Driver: @hannahkane
A: @simonwex @cassiemc @kaythaney 
R: @kristinashu @my-le 
C: @kaythaney @acabunoc @zee-moz @stephwright @auremoser 
I:

#### Overview
During this milestone we'll kick our research, IA, and UX pieces into high gear. The goal for the milestone is to gather more data (from both user research and looking at the current site's analytics) to inform the final site IA and homepage UX. Goal is not to have final IA and UX, since we may do another round of user feedback in the following heartbeat, but we should end the heartbeat with a couple data-informed versions of each to test.

Will also aim to finalize homepage content/copy.

#### Links
- [x] [Draft analytics report](https://github.com/mozillascience/site/issues/90)
- [x] [Complete phase 1 of research](https://github.com/mozillascience/site/issues/91)
- [ ] [Finalize visual aspects of brand direction](https://github.com/mozillascience/site/issues/80)
- [ ] [Create wireframes for Fellowships page](https://github.com/mozillascience/site/issues/93)
- [ ] [Create wireframes for Blog](https://github.com/mozillascience/site/issues/94)
- [ ] [Finalize Homepage wireframes](https://github.com/mozillascience/site/issues/95)
- [x] [Final content for homepage](https://github.com/mozillascience/site/issues/86)
- [x] [Final IA](https://github.com/mozillascience/site/issues/92)

**Comment by hannahkane** [comment]
Held a kickoff meeting this morning. First comment updated to reflect expected milestone deliverables.

**Comment by hannahkane** [comment]
Definitely seems on track. We've completed the first phase of research, and we have in-progress wireframes for the homepage, the blog, and the Fellowships page.

Meeting this afternoon to choose a direction for IA. Also getting very close on final content for the homepage.

We now have GA access, so the analytics report is unblocked.

**Comment by hannahkane** [comment]
We have final copy for the homepage now. yay! First comment updated.

**Comment by hannahkane** [comment]
I'm going to call this done.
