### ISSUE TITLE
CMS: Design and build templates that integrate with Calypso for first trial run

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#750]
#### DARCI
Driver: @hannahkane 
A: @davidascher 
R: @flukeout @vazquez @gvn @kristinashu @mmmavis
C: @cassiemc @simonwex  
I: Design team

#### Overview
We want to continue improving MozMaker, the Mofo-wide styles that will be applied to the new CMS work. For this next phase of work we've at least mentioned (and need to reach agreement on) key deliverables:

##### Templates
- [ ] finalize designs for first four layouts
  - [ ] [List](https://github.com/mozilla/cms-template-styles/issues/3)
  - [ ] [Step-by-step with side nav](https://github.com/mozilla/cms-template-styles/issues/4)
  - [ ] [Two-column, embedded video stream, with etherpad](https://github.com/mozilla/cms-template-styles/issues/5)
  - [ ] [Header image with CTA and CTAs in a row](https://github.com/mozilla/cms-template-styles/issues/6) - stretch goal
- [ ] Integrating @kristinashu's [colour work](https://github.com/MozillaFoundation/Design/issues/139)

##### Mozmaker
- [x] [Document how to use Mozmaker without the CMS](https://github.com/mozilla/mozmaker/issues/37)
- [ ] [Consider brand implications of using Mozmaker](https://github.com/mozilla/mozmaker/issues/32)
- [x] Nail down the architecture of [using sub-guides within Mozmaker](https://github.com/mozilla/mozmaker/issues/30)
- [x] [Finalize Mozmaker name](https://github.com/mozilla/mozmaker/issues/31)

##### Calypso
- [x] [Talk through user documentation as a team](https://github.com/mozilla/wp-calypso/issues/13)
- [ ] <s>[Add Mozmaker to Preview](https://github.com/mozilla/wp-calypso/issues/10)</s>
- [ ] [Create wp-api client that can be incorporated into teach.mozilla.org](https://github.com/mozilla/wp-calypso/issues/11)
- [ ] [Add ability to add new pages from within Calypso to Teach.m.o](https://github.com/mozilla/wp-calypso/issues/12)
- [ ] [Enable viewing of drafts through react-wp-api-client](https://github.com/mozilla/wp-calypso/issues/17)
- [ ] [Implement iframe preview functionality](https://github.com/mozilla/wp-calypso/issues/15)
- [ ] [Provide diagram/documentation that illustrates user flow](https://github.com/mozilla/wp-calypso/issues/14)

#### Links
* Current demo page: http://mozilla.github.io/mozmaker/demo/
* Planning work: https://github.com/MozillaFoundation/plan/issues/735
* Colour work in-progress: https://github.com/MozillaFoundation/Design/issues/139

**Comment by hannahkane** [comment]
Re: templates that need to be created—I could use an update on how finalized the existing ones are. I've seen versions of:
 * List (use case: Clubs Resources list) (I believe this one is done, but I don't know if it's had design review)
 * Step-by-step with side nav (use cases: Clubs Guides, Web Lit Curriculum, Participation Curriculum, MSL Guides) (not sure if this one has been foxlite'd)
 * Two-column, embedded video stream and etherpad (use case: Curriculum Workshop landing page) (design still being finalized, needs design and stakeholder review)

And it looks like the next one in the queue is Header image with CTA and CTAs in a row (see https://github.com/mozilla/wp-calypso/issues/7)

If we could finalize all four of those this heartbeat, I think that would be great.

**Comment by cassiemc** [comment]
I think this could use a clear driver, or co-drivers. Is that @hannahkane, @simonwex, me? All 3?

**Comment by OpenMatt** [comment]
next step: cassie, hannah, simon will update spec

**Comment by cassiemc** [comment]
@hannahkane should we kickoff this piece of work, separate to the MLN production work scheduling?

**Comment by hannahkane** [comment]
I don't think we need to. Have scheduled an hour for that meeting; should cover this along with the few other items in the works. Will update this ticket and make sure all tickets are filed in CMS and Teach repos in advance.

**Comment by cassiemc** [comment]
Suggest a new name – 'Design and build templates that integrate with the CMS for first trial run/s" or something like that. Scoping work here: https://public.etherpad-mozilla.org/p/thispadwilselfdestruct
Tracking work here: https://github.com/mozilla/foxlight/issues and ... CMS repo?

**Comment by hannahkane** [comment]
Successful kickoff meeting earlier today. First comment has been updated to reflect the work we currently think we can do this heartbeat, though we're having a more in-depth meeting soon, which may result in altering some tickets/milestone outcomes.

**Comment by hannahkane** [comment]
Documenting a related piece of work that happened: released static version of a specific use case to https://teach.mozilla.org/community/curriculum-workshop/. 

In an upcoming milestone, will move that page to CMS, but for now, back to the work in this ticket as described.

**Comment by ldecoursy** [comment]
@hannahkane Do you know if this will be ready in the CMS to use for the Mozilla Learning Community Call on March 24?

**Comment by hannahkane** [comment]
@ldecoursy - how far in advance of the call do we need it?

**Comment by ldecoursy** [comment]
We don't "need" it - we'll point to the Google Hangouts page and separate etherpad in the meantime. Could potentially use it to archive the call (and for future calls) if it's not ready yet. But if it is ready in the CMS, we'll use it for sure ;)

**Comment by hannahkane** [comment]
Will talk to the team about it at our next stand-up. I think it's useful to have real use cases driving the work forward, but also good to have back-up plans. :)

**Comment by hannahkane** [comment]
Updated the first comment. I'm going to call this "on track," but @simonwex—do you disagree?

**Comment by simonwex** [comment]
Don't disagree.

**Comment by hannahkane** [comment]
A few things reported during today's stand as possibly not going to finish this heartbeat: incorporating colour work into templates, and preview/view drafts in MozMaker. 

I'd still say this ticket is ontrack, given the spirit of what we were aiming to achieve this heartbeat.

**Comment by hannahkane** [comment]
Many of the sub-tasks will land by EOD today. Others will be moved to next heartbeat. Closing.
