### ISSUE TITLE
CMS: deliver complete workflow for publishing content from a template to a live webpage

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#766]
#### DARCI
Driver: @hannahkane
A: @simonwex @cassiemc 
R: @mmmavis @gvn @Pomax @flukeout @alicoding @cadecairos @vazquez 
C: @ldecoursy 
I:

#### Overview
Goals for the March 25 heartbeat are:
 - [ ] deliver the entire workflow from choosing a template to publishing, including save draft and preview
 - [ ] work with @ldecoursy to publish the Mozilla Learning Community Call landing page via CMS, in time for March 24th launch
 - [ ] final designs for templates: 3 CTAs, blogs, longform handbook, Group pages

#### Relevant Issues (more may be filed during the heartbeat as particular tasks emerge)
**Calypso**
 - [ ] [Design template for blog posts](https://github.com/mozilla/wp-calypso/issues/20)
 - [ ] [Enable viewing of drafts through react-wp-api-client](https://github.com/mozilla/wp-calypso/issues/17)
 - [ ] [Implement iframe preview functionality](https://github.com/mozilla/wp-calypso/issues/15)

**Templates**
 - [ ] [Finalize design for "Header image with CTA and CTAs in a row" layout](https://github.com/mozilla/mozmaker-templates/issues/6)
 - [ ] [Finalize design for "Multi-chapter Handbook" layout](https://github.com/mozilla/mozmaker-templates/issues/27)
 - [ ] [Finalize design for "Group page" layout](https://github.com/mozilla/mozmaker-templates/issues/28)

**Teach**
 - [ ] [Build MLN Community Call landing page and archive pages with CMS](https://github.com/mozilla/teach.mozilla.org/issues/1697)

**Comment by hannahkane** [comment]
Heartbeat kickoff meeting happened - add'l tickets to be filed by @mmmavis and @gvn 

New templates are P2—priority is delivering the end-to-end workflow including UX

**Comment by hannahkane** [comment]
This ticket is no longer reflective of the work we did in this heartbeat. By the end of the heartbeat we'll ship an **end-to-end workflow for creating a simple (one partial) page and deploying to the Teach site, including preview.**

Known blocker around hosting. Need update from @simonwex or @cadecairos about whether that's going to cause this work to roll over into the next heartbeat.

**Comment by hannahkane** [comment]
Closing this issue because it's largely complete. Will file a separate ticket for releasing CMS v1.
