### ISSUE TITLE
Science Site Refresh 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#785]
## Engineering:
 - [ ] Projects pages and functionality (3.0 and 3.1 content) (with search/sort/filter)
  - [ ] [API to support Search/Sort/Filter](https://github.com/mozilla/science.mozilla.org/issues/116) 
  - [ ] [Front-end ](https://github.com/mozilla/science.mozilla.org/issues/114)
 - [ ] Homepage
  - [ ] [Front-end for https://redpen.io/jv7dd38e552814c20a](https://github.com/mozilla/science.mozilla.org/issues/115)

## Design:
 - [x] [Comps for all Events-related pages](https://github.com/mozilla/science.mozilla.org/issues/117)
 - [x] [Comps for all Fellowships-related pages](https://github.com/mozilla/science.mozilla.org/issues/118)
 - [x] [Blog wireframes using onesie](https://github.com/mozilla/science.mozilla.org/issues/119)

**Comment by hannahkane** [comment]
Updated first ticket to reflect agreed-upon deliverables

**Comment by hannahkane** [comment]
This team added estimations to stories at the beginning of the heartbeat, so we can show a burndown chart using zenhub:

![screen shot 2016-04-14 at 3 21 21 pm](https://cloud.githubusercontent.com/assets/8389648/14546387/eaa622a4-0259-11e6-9a7f-e3330a5f01a8.png)

The blue line shows story points completed (as opposed to number of issues closed). The orange line is the ideal burndown based on the number of story points in the heartbeat and the number of days.

The burndown is flawed for two reasons: 1) it assumes we work on the weekends, and 2) we weren't able to estimate every story. However, even with those caveats I think we can say we have a good chance of completing all of the stories in this heartbeat.

Because we have a pressing deadline for this project (the MSL Global Sprint), we are working on a contingency plan as well. The contingency plan is to make the necessary content and IA changes to the current site to effectively convey recent changes to the MSL program. We'll make a decision on April 22nd whether to switch resources over to implementing the contingency plan.

**Comment by hannahkane** [comment]
Mid-sprint burndown. Pretty close to on-target.

![screen shot 2016-04-18 at 3 16 57 pm](https://cloud.githubusercontent.com/assets/8389648/14621562/a585c04a-0578-11e6-8530-a8545154c66f.png)

cc @simonwex @chrislarry33 @kaythaney who I think all care about this project :) See above for info about what the burndown chart is showing, and feel free to ask questions here.

**Comment by hannahkane** [comment]
Today's burndown:

![screen shot 2016-04-20 at 2 47 16 pm](https://cloud.githubusercontent.com/assets/8389648/14691582/d667a298-0706-11e6-8cb2-471486394bf9.png)

**Comment by simonwex** [comment]
I love watching this burn down.

**Comment by hannahkane** [comment]
Closing this as the issue for the next stage of this has been filed.
