### ISSUE TITLE
Clubs: application workflow and content changes

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#798]
#### Overview
We want to:
 * increase Club Captain application completion rate by reducing the number of steps for the applicant
 * ensure all new CCs are effectively onboarded 
 * recognize Regional Coordinators, and lend legitimacy to their outreach efforts

In this heartbeat, we'll take the following steps towards these goals
 * [x] [Make changes to the CC application form](https://github.com/mozilla/teach.mozilla.org/issues/1822)
 * [ ] Trigger automatic email upon approval](https://github.com/mozilla/teach.mozilla.org/issues/1826)
 * [x] [Add new content to the Clubs page](https://github.com/mozilla/teach.mozilla.org/issues/1605)
 * [ ] <s>[Build a page for RC bios](https://github.com/mozilla/teach.mozilla.org/issues/1815) </s>

**Comment by hannahkane** [comment]
Application form changes are in progress. Other items might be at risk.

**Comment by hannahkane** [comment]
Removing the automatic email from this heartbeat as it's unlikely to get done.

**Comment by hannahkane** [comment]
Send instructions to @amirad to create the RC bios page with the CMS on a staging server. Yay!

**Comment by hannahkane** [comment]
Changing scope of these tickets to be design only; implementation will happen in a future heartbeat.

**Comment by hannahkane** [comment]
Rolling this to next heartbeat. Design will be nearly finished, but implementation is for May 20.

**Comment by hannahkane** [comment]
Unfortunately, have to remove this from the May 20 sprint, due to lack of engineering resources.

**Comment by hannahkane** [comment]
The revised application form is on track for this heartbeat, and the RC bios page is in progress (dependent upon deploying some fixes to Calypso).

Hoping to have time to get a final design for the Clubs page, but pending final copy.

**Comment by hannahkane** [comment]
Rolling into the next heartbeat.

**Comment by hannahkane** [comment]
New application form is in production.

**Comment by hannahkane** [comment]
Clubs page layout changes are live.

**Comment by hannahkane** [comment]
This is all being tracked in Learning site repo, so I'm closing this here. Will use Plan repo exclusively for pan-Mofo projects.
