### ISSUE TITLE
MozFest Design Prep

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#821]
As per the [design brief](https://docs.google.com/document/d/1f-ybB8x6HJ2F4JyDnN8wUdyMcO9b7VpQCLGINGgTKuA/edit), we'll spend the July 22 heartbeat preparing for the upcoming design work needed for MozFest 2016.

The production team will deliver:
 - [x] [Hold a design retrospective](https://github.com/MozillaFoundation/Mozfest2016_production/issues/15)
 - [x] [Review design assets list](https://github.com/MozillaFoundation/Mozfest2016_production/issues/11)
 - [x] [Create moodboards](https://github.com/MozillaFoundation/Mozfest2016_production/issues/14)

And @xmatthewx will deliver:
 - [x] [Write job description for contractor](https://github.com/MozillaFoundation/Mozfest2016_production/issues/12)
 - [x] [ID places to post job description](https://github.com/MozillaFoundation/Mozfest2016_production/issues/13)

**Comment by hannahkane** [comment]
I believe all the items in this list are done, so I'm going to close this ticket. @edrushka - if useful, feel free to file a planning ticket that better represents the upcoming heartbeat.
